import { Routine } from '../types';

export const preBuiltRoutines: Routine[] = [
  // ─── TIME OF DAY: MORNING ────────────────────────────────────────────────────

  {
    id: 'morning-wake-up',
    name: 'Wake Up',
    description:
      'A gentle 5-minute wake-up sequence that mobilizes the spine and shoulders to ease your body out of sleep. Perfect for mornings when you want a quick, low-effort start.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['neck', 'upper-back', 'lower-back', 'shoulders'],
    categories: ['morning'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 1 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 2 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-knee-to-chest', holdSeconds: 30, order: 4 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 5 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 6 },
    ],
    tags: ['morning', 'wake-up', 'gentle', 'spine', 'beginner', 'quick'],
  },

  {
    id: 'morning-flow',
    name: 'Morning Flow',
    description:
      'A 10-minute flowing morning routine that progressively warms up the full body, opening the chest, hips, and back to build energy and mobility for the day ahead.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['neck', 'shoulders', 'upper-back', 'lower-back', 'hips', 'chest'],
    categories: ['morning'],
    exercises: [
      { exerciseId: 'neck-roll', holdSeconds: 30, order: 1 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 2 },
      { exerciseId: 'arm-circles', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-sphinx-pose', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 6 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 7 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 8 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 9 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 10 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 11 },
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 12 },
    ],
    tags: ['morning', 'flow', 'full-body', 'energy', 'intermediate', 'warm-up'],
  },

  {
    id: 'morning-sunrise-stretch',
    name: 'Sunrise Stretch',
    description:
      'A comprehensive 15-minute sunrise routine that works through every major muscle group from neck to calves, building warmth, flexibility, and mental clarity before your day begins.',
    difficulty: 'intermediate',
    durationMinutes: 15,
    bodyAreas: ['neck', 'shoulders', 'chest', 'upper-back', 'lower-back', 'hips', 'hamstrings'],
    categories: ['morning'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 1 },
      { exerciseId: 'neck-forward-fold', holdSeconds: 30, order: 2 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 3 },
      { exerciseId: 'arm-circles', holdSeconds: 30, order: 4 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 6 },
      { exerciseId: 'back-sphinx-pose', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 8 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 9 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 10 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 11 },
      { exerciseId: 'butterfly-stretch', holdSeconds: 30, order: 12 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 13 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 14 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 15 },
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 16 },
      { exerciseId: 'full-body-star-stretch', holdSeconds: 30, order: 17 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 18 },
    ],
    tags: ['morning', 'sunrise', 'full-body', 'comprehensive', 'intermediate', 'flexibility'],
  },

  // ─── TIME OF DAY: MIDDAY ─────────────────────────────────────────────────────

  {
    id: 'midday-desk-break',
    name: 'Desk Break',
    description:
      'A quick 5-minute desk-break routine targeting the neck, shoulders, and back to counteract the effects of prolonged sitting. No floor work required — everything can be done standing or seated.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['neck', 'shoulders', 'upper-back', 'lower-back'],
    categories: ['midday'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 1 },
      { exerciseId: 'neck-forward-fold', holdSeconds: 30, order: 2 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 3 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-standing-back-extension', holdSeconds: 20, order: 5 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 6 },
    ],
    tags: ['midday', 'desk', 'office', 'neck', 'shoulders', 'beginner', 'no-floor', 'quick'],
  },

  {
    id: 'midday-office-reset',
    name: 'Office Reset',
    description:
      'A 10-minute midday routine designed to reverse the hunched desk posture. Focuses on opening the chest, releasing the neck, and decompressing the spine — all with minimal space needed.',
    difficulty: 'beginner',
    durationMinutes: 10,
    bodyAreas: ['neck', 'shoulders', 'chest', 'upper-back', 'lower-back'],
    categories: ['midday'],
    exercises: [
      { exerciseId: 'chin-tuck', holdSeconds: 20, order: 1 },
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 2 },
      { exerciseId: 'neck-roll', holdSeconds: 30, order: 3 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 4 },
      { exerciseId: 'cross-body-shoulder-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'chest-clasp-behind-back', holdSeconds: 30, order: 6 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-standing-back-extension', holdSeconds: 20, order: 8 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 9 },
      { exerciseId: 'back-pelvic-tilt', holdSeconds: 20, order: 10 },
    ],
    tags: ['midday', 'office', 'posture', 'desk', 'beginner', 'chest', 'neck'],
  },

  {
    id: 'midday-mobility',
    name: 'Midday Mobility',
    description:
      'A 15-minute midday session that combines postural resets with hip and thoracic mobility work, giving you a meaningful movement break that will boost afternoon energy and focus.',
    difficulty: 'intermediate',
    durationMinutes: 15,
    bodyAreas: ['neck', 'shoulders', 'chest', 'upper-back', 'lower-back', 'hips'],
    categories: ['midday'],
    exercises: [
      { exerciseId: 'chin-tuck', holdSeconds: 20, order: 1 },
      { exerciseId: 'levator-scapulae-stretch', holdSeconds: 30, order: 2 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 3 },
      { exerciseId: 'eagle-arms', holdSeconds: 30, order: 4 },
      { exerciseId: 'chest-doorway-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-thoracic-rotation', holdSeconds: 30, order: 6 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 8 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 9 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 10 },
      { exerciseId: '90-90-stretch', holdSeconds: 30, order: 11 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 12 },
      { exerciseId: 'full-body-lunge-with-twist', holdSeconds: 30, order: 13 },
      { exerciseId: 'back-standing-back-extension', holdSeconds: 20, order: 14 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 15 },
    ],
    tags: ['midday', 'mobility', 'thoracic', 'hips', 'intermediate', 'energy', 'posture'],
  },

  // ─── TIME OF DAY: EVENING ────────────────────────────────────────────────────

  {
    id: 'evening-wind-down',
    name: 'Wind Down',
    description:
      'A calming 5-minute evening stretch to signal to your body that the day is ending. Gentle, floor-based movements decompress the spine and settle the nervous system before sleep.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['lower-back', 'hips', 'upper-back'],
    categories: ['evening'],
    exercises: [
      { exerciseId: 'back-knee-to-chest', holdSeconds: 30, order: 1 },
      { exerciseId: 'back-pelvic-tilt', holdSeconds: 20, order: 2 },
      { exerciseId: 'reclined-hip-opener', holdSeconds: 30, order: 3 },
      { exerciseId: 'happy-baby', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 5 },
    ],
    tags: ['evening', 'wind-down', 'sleep', 'gentle', 'beginner', 'floor', 'relaxation'],
  },

  {
    id: 'evening-unwind',
    name: 'Evening Unwind',
    description:
      'A soothing 10-minute evening session blending spinal release, hip opening, and chest work to melt away the day\'s tension and prepare the body and mind for restful sleep.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['neck', 'shoulders', 'upper-back', 'lower-back', 'hips', 'chest'],
    categories: ['evening'],
    exercises: [
      { exerciseId: 'neck-forward-fold', holdSeconds: 30, order: 1 },
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 2 },
      { exerciseId: 'thread-the-needle', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 6 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'happy-baby', holdSeconds: 30, order: 8 },
      { exerciseId: 'chest-floor-opener', holdSeconds: 30, order: 9 },
      { exerciseId: 'reclined-hip-opener', holdSeconds: 30, order: 10 },
      { exerciseId: 'back-knee-to-chest', holdSeconds: 30, order: 11 },
    ],
    tags: ['evening', 'unwind', 'relaxation', 'sleep', 'intermediate', 'restorative'],
  },

  {
    id: 'evening-deep-relax',
    name: 'Deep Relax',
    description:
      'A thorough 20-minute deep relaxation sequence using long, passive holds that release accumulated muscular tension from head to toe. Ideal for high-stress days or as a weekend wind-down ritual.',
    difficulty: 'expert',
    durationMinutes: 20,
    bodyAreas: ['neck', 'shoulders', 'chest', 'upper-back', 'lower-back', 'hips', 'hamstrings'],
    categories: ['evening'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 45, order: 1 },
      { exerciseId: 'neck-forward-fold', holdSeconds: 45, order: 2 },
      { exerciseId: 'levator-scapulae-stretch', holdSeconds: 45, order: 3 },
      { exerciseId: 'thread-the-needle', holdSeconds: 45, order: 4 },
      { exerciseId: 'chest-floor-opener', holdSeconds: 45, order: 5 },
      { exerciseId: 'back-childs-pose', holdSeconds: 45, order: 6 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-sphinx-pose', holdSeconds: 45, order: 8 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 45, order: 9 },
      { exerciseId: 'pigeon-pose', holdSeconds: 45, order: 10 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 45, order: 11 },
      { exerciseId: 'butterfly-stretch', holdSeconds: 45, order: 12 },
      { exerciseId: 'happy-baby', holdSeconds: 45, order: 13 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 45, order: 14 },
      { exerciseId: 'reclined-hip-opener', holdSeconds: 45, order: 15 },
      { exerciseId: 'back-knee-to-chest', holdSeconds: 45, order: 16 },
    ],
    tags: ['evening', 'deep-relax', 'restorative', 'long-hold', 'expert', 'sleep', 'stress-relief'],
  },

  // ─── TIME OF DAY: POST-WORKOUT ───────────────────────────────────────────────

  {
    id: 'post-workout-quick-cool-down',
    name: 'Quick Cool Down',
    description:
      'A fast 5-minute post-workout cool-down targeting the most common tight spots after exercise: quads, hamstrings, calves, and hip flexors. Helps reduce next-day soreness.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['quadriceps', 'hamstrings', 'hips', 'calves'],
    categories: ['post-workout'],
    exercises: [
      { exerciseId: 'standing-quad-stretch', holdSeconds: 30, order: 1 },
      { exerciseId: 'standing-hamstring-stretch', holdSeconds: 30, order: 2 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 3 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 6 },
    ],
    tags: ['post-workout', 'cool-down', 'recovery', 'legs', 'beginner', 'quick'],
  },

  {
    id: 'post-workout-recovery-flow',
    name: 'Recovery Flow',
    description:
      'A 10-minute post-workout recovery flow that addresses the full lower body and releases spinal compression built up during training. Ideal after runs, cycling, or lower-body gym sessions.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['quadriceps', 'hamstrings', 'hips', 'calves', 'lower-back'],
    categories: ['post-workout'],
    exercises: [
      { exerciseId: 'standing-quad-stretch', holdSeconds: 30, order: 1 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 2 },
      { exerciseId: 'lizard-pose', holdSeconds: 45, order: 3 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 5 },
      { exerciseId: 'standing-hamstring-stretch', holdSeconds: 30, order: 6 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'soleus-stretch', holdSeconds: 30, order: 8 },
      { exerciseId: 'back-knee-to-chest', holdSeconds: 30, order: 9 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 10 },
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 11 },
    ],
    tags: ['post-workout', 'recovery', 'legs', 'hips', 'intermediate', 'running', 'cycling'],
  },

  {
    id: 'post-workout-deep-recovery',
    name: 'Deep Recovery',
    description:
      'A thorough 15-minute deep recovery session using prolonged holds to systematically release tight muscles and restore full range of motion after an intense training session.',
    difficulty: 'expert',
    durationMinutes: 15,
    bodyAreas: ['quadriceps', 'hamstrings', 'hips', 'calves', 'lower-back', 'upper-back', 'shoulders'],
    categories: ['post-workout'],
    exercises: [
      { exerciseId: 'full-body-downward-dog', holdSeconds: 45, order: 1 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 45, order: 2 },
      { exerciseId: 'lizard-pose', holdSeconds: 45, order: 3 },
      { exerciseId: 'pigeon-pose', holdSeconds: 45, order: 4 },
      { exerciseId: '90-90-stretch', holdSeconds: 45, order: 5 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 45, order: 6 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 45, order: 7 },
      { exerciseId: 'wide-leg-forward-bend', holdSeconds: 45, order: 8 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 9 },
      { exerciseId: 'soleus-stretch', holdSeconds: 30, order: 10 },
      { exerciseId: 'back-childs-pose', holdSeconds: 45, order: 11 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 12 },
      { exerciseId: 'cross-body-shoulder-stretch', holdSeconds: 30, order: 13 },
    ],
    tags: ['post-workout', 'deep-recovery', 'expert', 'long-hold', 'full-body', 'athletic'],
  },

  // ─── BY BODY AREA ─────────────────────────────────────────────────────────────

  {
    id: 'neck-relief',
    name: 'Neck Relief',
    description:
      'A targeted 5-minute neck routine that addresses all planes of cervical movement to relieve tension headaches, tech-neck, and stiffness from screen time or poor sleeping position.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['neck'],
    categories: [],
    exercises: [
      { exerciseId: 'chin-tuck', holdSeconds: 20, order: 1 },
      { exerciseId: 'neck-forward-fold', holdSeconds: 30, order: 2 },
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 3 },
      { exerciseId: 'neck-roll', holdSeconds: 30, order: 4 },
      { exerciseId: 'levator-scapulae-stretch', holdSeconds: 30, order: 5 },
    ],
    tags: ['neck', 'tech-neck', 'headache', 'beginner', 'office', 'tension'],
  },

  {
    id: 'shoulder-opener',
    name: 'Shoulder Opener',
    description:
      'A 10-minute shoulder routine that mobilizes the glenohumeral joint, loosens the rotator cuff, and opens the front of the shoulders to counteract rounded-shoulder posture.',
    difficulty: 'beginner',
    durationMinutes: 10,
    bodyAreas: ['shoulders', 'upper-back'],
    categories: [],
    exercises: [
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 1 },
      { exerciseId: 'arm-circles', holdSeconds: 30, order: 2 },
      { exerciseId: 'cross-body-shoulder-stretch', holdSeconds: 30, order: 3 },
      { exerciseId: 'overhead-tricep-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'doorway-chest-shoulder-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'chest-clasp-behind-back', holdSeconds: 30, order: 6 },
      { exerciseId: 'eagle-arms', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-prayer-stretch', holdSeconds: 30, order: 8 },
    ],
    tags: ['shoulders', 'rotator-cuff', 'posture', 'beginner', 'upper-body', 'mobility'],
  },

  {
    id: 'upper-back-release',
    name: 'Upper Back Release',
    description:
      'A 10-minute routine specifically targeting the thoracic spine, rhomboids, and upper trapezius — the areas most burdened by desk work, driving, and forward-head posture.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['upper-back', 'shoulders'],
    categories: [],
    exercises: [
      { exerciseId: 'back-thoracic-rotation', holdSeconds: 30, order: 1 },
      { exerciseId: 'thread-the-needle', holdSeconds: 30, order: 2 },
      { exerciseId: 'eagle-arms', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-prayer-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 6 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 7 },
      { exerciseId: 'chest-floor-opener', holdSeconds: 30, order: 8 },
    ],
    tags: ['upper-back', 'thoracic', 'rhomboids', 'posture', 'intermediate', 'desk-workers'],
  },

  {
    id: 'lower-back-relief',
    name: 'Lower Back Relief',
    description:
      'A 10-minute gentle lower back routine that decompresses lumbar vertebrae, activates deep core stabilizers, and releases hip flexors — addressing the root causes of everyday back discomfort.',
    difficulty: 'beginner',
    durationMinutes: 10,
    bodyAreas: ['lower-back', 'hips'],
    categories: [],
    exercises: [
      { exerciseId: 'back-pelvic-tilt', holdSeconds: 20, order: 1 },
      { exerciseId: 'back-knee-to-chest', holdSeconds: 30, order: 2 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-sphinx-pose', holdSeconds: 30, order: 5 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 6 },
      { exerciseId: 'happy-baby', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 8 },
      { exerciseId: 'back-standing-back-extension', holdSeconds: 20, order: 9 },
    ],
    tags: ['lower-back', 'back-pain', 'lumbar', 'beginner', 'core', 'decompression'],
  },

  {
    id: 'hip-opener',
    name: 'Hip Opener',
    description:
      'A 10-minute hip-focused routine that targets every major movement pattern of the hip joint: flexion, extension, external rotation, and adduction. Ideal for desk workers and athletes alike.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['hips', 'lower-back'],
    categories: [],
    exercises: [
      { exerciseId: 'hip-circles', holdSeconds: 30, order: 1 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 2 },
      { exerciseId: 'butterfly-stretch', holdSeconds: 30, order: 3 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: '90-90-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'pigeon-pose', holdSeconds: 45, order: 6 },
      { exerciseId: 'frog-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'reclined-hip-opener', holdSeconds: 30, order: 8 },
    ],
    tags: ['hips', 'hip-flexors', 'glutes', 'intermediate', 'mobility', 'sitting'],
  },

  {
    id: 'hamstring-flexibility',
    name: 'Hamstring Flexibility',
    description:
      'A 10-minute hamstring-focused routine progressing from dynamic warm-up to deep static holds to systematically lengthen the posterior thigh and reduce lower back strain.',
    difficulty: 'beginner',
    durationMinutes: 10,
    bodyAreas: ['hamstrings', 'lower-back', 'calves'],
    categories: [],
    exercises: [
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 1 },
      { exerciseId: 'toe-touch', holdSeconds: 30, order: 2 },
      { exerciseId: 'standing-hamstring-stretch', holdSeconds: 30, order: 3 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 4 },
      { exerciseId: 'full-body-downward-dog', holdSeconds: 30, order: 5 },
      { exerciseId: 'lizard-pose', holdSeconds: 45, order: 6 },
      { exerciseId: 'wide-leg-forward-bend', holdSeconds: 30, order: 7 },
    ],
    tags: ['hamstrings', 'flexibility', 'posterior-chain', 'beginner', 'lower-body', 'back-pain'],
  },

  {
    id: 'leg-day-recovery',
    name: 'Leg Day Recovery',
    description:
      'A 15-minute recovery session designed for after lower-body strength training, covering quads, hamstrings, calves, hip flexors, and IT band to minimize soreness and restore full range of motion.',
    difficulty: 'intermediate',
    durationMinutes: 15,
    bodyAreas: ['quadriceps', 'hamstrings', 'hips', 'calves'],
    categories: ['post-workout'],
    exercises: [
      { exerciseId: 'standing-quad-stretch', holdSeconds: 30, order: 1 },
      { exerciseId: 'lying-quad-stretch', holdSeconds: 30, order: 2 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 3 },
      { exerciseId: 'it-band-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'pigeon-pose', holdSeconds: 45, order: 6 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 7 },
      { exerciseId: 'wide-leg-forward-bend', holdSeconds: 30, order: 8 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 9 },
      { exerciseId: 'soleus-stretch', holdSeconds: 30, order: 10 },
      { exerciseId: 'wall-calf-stretch', holdSeconds: 30, order: 11 },
      { exerciseId: 'ankle-circles', holdSeconds: 20, order: 12 },
      { exerciseId: 'inner-thigh-squat', holdSeconds: 30, order: 13 },
    ],
    tags: ['legs', 'quads', 'hamstrings', 'calves', 'recovery', 'intermediate', 'gym', 'soreness'],
  },

  {
    id: 'chest-and-shoulders',
    name: 'Chest & Shoulders',
    description:
      'A 10-minute routine focused on opening the anterior chest and releasing the front of the shoulders — directly countering the internal rotation and compression caused by keyboard use and forward-leaning postures.',
    difficulty: 'beginner',
    durationMinutes: 10,
    bodyAreas: ['chest', 'shoulders', 'upper-back'],
    categories: [],
    exercises: [
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 1 },
      { exerciseId: 'arm-circles', holdSeconds: 30, order: 2 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 3 },
      { exerciseId: 'chest-clasp-behind-back', holdSeconds: 30, order: 4 },
      { exerciseId: 'chest-doorway-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: 'chest-wall-stretch', holdSeconds: 30, order: 6 },
      { exerciseId: 'doorway-chest-shoulder-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'chest-floor-opener', holdSeconds: 30, order: 8 },
    ],
    tags: ['chest', 'shoulders', 'pectorals', 'beginner', 'posture', 'upper-body', 'desk'],
  },

  {
    id: 'full-body-flow',
    name: 'Full Body Flow',
    description:
      'A well-rounded 15-minute full-body routine that moves through every major joint and muscle group in a logical, flowing sequence — a complete stretch session when time allows.',
    difficulty: 'intermediate',
    durationMinutes: 15,
    bodyAreas: ['full-body', 'neck', 'shoulders', 'upper-back', 'lower-back', 'hips', 'hamstrings'],
    categories: ['morning', 'evening'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 1 },
      { exerciseId: 'shoulder-roll', holdSeconds: 30, order: 2 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 3 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 4 },
      { exerciseId: 'chest-expansion', holdSeconds: 30, order: 5 },
      { exerciseId: 'full-body-lunge-with-twist', holdSeconds: 30, order: 6 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 8 },
      { exerciseId: 'full-body-downward-dog', holdSeconds: 30, order: 9 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 10 },
      { exerciseId: 'pigeon-pose', holdSeconds: 45, order: 11 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 12 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 13 },
      { exerciseId: 'full-body-rag-doll', holdSeconds: 30, order: 14 },
    ],
    tags: ['full-body', 'flow', 'intermediate', 'comprehensive', 'balanced', 'flexibility'],
  },

  {
    id: 'core-and-back',
    name: 'Core & Back',
    description:
      'A 10-minute session targeting the deep core and the entire spine — activating stabilizing muscles while releasing chronic tightness in both the upper and lower back.',
    difficulty: 'intermediate',
    durationMinutes: 10,
    bodyAreas: ['lower-back', 'upper-back'],
    categories: [],
    exercises: [
      { exerciseId: 'back-pelvic-tilt', holdSeconds: 20, order: 1 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 2 },
      { exerciseId: 'back-sphinx-pose', holdSeconds: 30, order: 3 },
      { exerciseId: 'back-cobra-pose', holdSeconds: 30, order: 4 },
      { exerciseId: 'back-thoracic-rotation', holdSeconds: 30, order: 5 },
      { exerciseId: 'back-seated-spinal-twist', holdSeconds: 30, order: 6 },
      { exerciseId: 'back-prayer-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'back-childs-pose', holdSeconds: 30, order: 8 },
      { exerciseId: 'back-standing-back-extension', holdSeconds: 20, order: 9 },
    ],
    tags: ['core', 'back', 'spine', 'lumbar', 'thoracic', 'intermediate', 'stability'],
  },

  {
    id: 'lower-body-flexibility',
    name: 'Lower Body Flexibility',
    description:
      'A thorough 15-minute lower body flexibility routine covering the hips, hamstrings, quads, adductors, and calves to build lasting posterior chain length and functional leg mobility.',
    difficulty: 'intermediate',
    durationMinutes: 15,
    bodyAreas: ['hips', 'hamstrings', 'quadriceps', 'calves'],
    categories: [],
    exercises: [
      { exerciseId: 'hip-circles', holdSeconds: 30, order: 1 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 2 },
      { exerciseId: 'standing-quad-stretch', holdSeconds: 30, order: 3 },
      { exerciseId: 'it-band-stretch', holdSeconds: 30, order: 4 },
      { exerciseId: 'figure-4-stretch', holdSeconds: 30, order: 5 },
      { exerciseId: '90-90-stretch', holdSeconds: 30, order: 6 },
      { exerciseId: 'butterfly-stretch', holdSeconds: 30, order: 7 },
      { exerciseId: 'inner-thigh-squat', holdSeconds: 30, order: 8 },
      { exerciseId: 'seated-forward-fold', holdSeconds: 30, order: 9 },
      { exerciseId: 'wide-leg-forward-bend', holdSeconds: 30, order: 10 },
      { exerciseId: 'standing-calf-stretch', holdSeconds: 30, order: 11 },
      { exerciseId: 'soleus-stretch', holdSeconds: 30, order: 12 },
      { exerciseId: 'ankle-circles', holdSeconds: 20, order: 13 },
    ],
    tags: ['lower-body', 'legs', 'flexibility', 'hips', 'hamstrings', 'intermediate', 'comprehensive'],
  },

  {
    id: 'quick-full-body',
    name: 'Quick Full Body',
    description:
      'A 5-minute full-body hit when you only have a few minutes to spare — one stretch per major zone, covering the neck, spine, hips, and legs in a single efficient sequence.',
    difficulty: 'beginner',
    durationMinutes: 5,
    bodyAreas: ['full-body', 'neck', 'upper-back', 'lower-back', 'hips', 'hamstrings'],
    categories: ['morning', 'midday'],
    exercises: [
      { exerciseId: 'neck-side-tilt', holdSeconds: 30, order: 1 },
      { exerciseId: 'back-cat-cow', holdSeconds: 30, order: 2 },
      { exerciseId: 'hip-flexor-lunge', holdSeconds: 30, order: 3 },
      { exerciseId: 'toe-touch', holdSeconds: 30, order: 4 },
      { exerciseId: 'full-body-standing-side-bend', holdSeconds: 30, order: 5 },
      { exerciseId: 'full-body-upward-salute', holdSeconds: 30, order: 6 },
    ],
    tags: ['full-body', 'quick', 'beginner', 'efficient', 'five-minutes', 'any-time'],
  },
];
