import { Exercise } from '../types';

export const backExercises: Exercise[] = [
  {
    id: 'back-cat-cow',
    name: 'Cat-Cow',
    difficulty: 'beginner',
    targetMuscles: ['erector spinae', 'multifidus', 'rectus abdominis', 'trapezius'],
    bodyAreas: ['upper-back', 'lower-back'],
    illustrationFile: 'back-cat-cow.png',
    illustrationPrompt:
      'Flat vector illustration of a person on hands and knees alternating between arching their back upward like a cat and dropping their belly downward like a cow, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Begin on all fours with your wrists directly under your shoulders and knees under your hips.',
      'Ensure your spine is in a neutral position, parallel to the floor.',
      'Inhale slowly as you drop your belly toward the floor, lifting your chest and tailbone toward the ceiling (Cow position).',
      'Pause briefly at the bottom of the inhale.',
      'Exhale as you round your spine toward the ceiling, tucking your chin to your chest and drawing your tailbone under (Cat position).',
      'Pause briefly at the top of the exhale.',
      'Continue flowing between Cat and Cow positions, synchronizing each movement with your breath.',
      'Repeat for 8–10 breath cycles, then return to neutral.',
    ],
    tips: [
      'Move slowly and deliberately — the stretch comes from the motion, not the endpoint.',
      'Keep your arms straight but not locked; think of pressing the floor gently away.',
      'In Cow, avoid collapsing into your lower back — the curve should be distributed evenly.',
      'In Cat, imagine pulling your navel up toward your spine to deepen the stretch.',
      'If your wrists are uncomfortable, make fists or place forearms on the floor instead.',
    ],
    modifications: {
      easier: 'Perform seated in a chair: place hands on knees and alternate between rounding and arching the spine.',
      harder: 'Add a lateral side bend at the end of each Cat position, dropping one hip toward the floor to work the obliques.',
    },
    benefits: [
      'Mobilizes the entire spine from tailbone to skull',
      'Stretches the erector spinae, trapezius, and abdominal muscles',
      'Improves spinal flexion and extension range of motion',
      'Gently massages the intervertebral discs and surrounding soft tissue',
      'Coordinates breath with movement to reduce tension and stress',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-childs-pose',
    name: "Child's Pose",
    difficulty: 'beginner',
    targetMuscles: ['latissimus dorsi', 'erector spinae', 'gluteus maximus', 'hip flexors'],
    bodyAreas: ['upper-back', 'lower-back', 'hips'],
    illustrationFile: 'back-childs-pose.png',
    illustrationPrompt:
      "Flat vector illustration of a person kneeling with their torso folded forward over their thighs, arms stretched out long in front of them, forehead resting on the floor in child's pose, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px",
    instructions: [
      'Kneel on the floor and sit back on your heels, bringing your big toes together.',
      'Separate your knees to about hip-width apart, or wider for a deeper hip opener.',
      'Exhale and fold your torso forward between your thighs, lowering your chest toward the floor.',
      'Extend your arms long in front of you with palms facing down, or rest them alongside your body with palms up.',
      'Allow your forehead to rest on the mat.',
      'Let gravity gently pull your hips back toward your heels with each exhale.',
      'Hold the position, breathing deeply into your back body and expanding your ribcage with each inhale.',
      'To release, walk your hands back toward you and slowly press up to seated.',
    ],
    tips: [
      'If your hips do not reach your heels, place a folded blanket between your thighs and calves.',
      'To target the upper back more, walk hands further forward and press the floor away actively.',
      'Focus on sending breath into the back of the ribcage to feel the stretch deepen on each inhale.',
      'Keep your neck long — avoid cranking the head backward.',
      'If your knees are uncomfortable, try a wider stance or reduce the bend with a prop underneath.',
    ],
    modifications: {
      easier: 'Place a pillow or bolster under your torso so your chest rests on it, reducing the depth of the fold.',
      harder: 'Walk hands to one side and hold for 15 seconds, then the other, to add a lateral thoracic stretch.',
    },
    benefits: [
      'Passively lengthens the latissimus dorsi and erector spinae',
      'Decompresses the lumbar spine by gently traction-stretching the vertebrae',
      'Opens the hips and stretches the gluteus maximus',
      'Calms the nervous system and relieves stress-related back tension',
      'Improves spinal flexion and overall back mobility',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-seated-spinal-twist',
    name: 'Seated Spinal Twist',
    difficulty: 'beginner',
    targetMuscles: ['obliques', 'erector spinae', 'multifidus', 'piriformis', 'rhomboids'],
    bodyAreas: ['upper-back', 'lower-back'],
    illustrationFile: 'back-seated-spinal-twist.png',
    illustrationPrompt:
      'Flat vector illustration of a person seated on the floor with legs extended, one knee bent and foot planted outside the opposite thigh, torso rotated toward the bent knee with one arm wrapped around it, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Sit on the floor with both legs extended straight in front of you.',
      'Bend your right knee and place your right foot flat on the floor just outside your left thigh.',
      'Sit tall, lengthening through the crown of your head to avoid collapsing.',
      'Inhale to grow tall, then exhale as you rotate your torso to the right.',
      'Wrap your left arm around your right knee, or hook your left elbow outside your right knee for leverage.',
      'Place your right hand on the floor behind your right hip for support.',
      'With each inhale, grow taller. With each exhale, deepen the rotation slightly.',
      'Hold for the full duration, then inhale to unwind and repeat on the left side.',
    ],
    tips: [
      'The twist originates from the base of your spine — do not force the rotation from your shoulders.',
      'Keep both sitting bones grounded to prevent the pelvis from rotating with the twist.',
      'Gaze past your back shoulder to encourage rotation through the cervical spine.',
      'Do not hold your breath — let each exhale be your cue to deepen the twist.',
      'If sitting straight is difficult, sit on a folded blanket to tilt the pelvis forward slightly.',
    ],
    modifications: {
      easier: 'Keep both legs extended and simply rotate the torso to one side with hands on the floor behind you.',
      harder: 'Bind the arms by threading one hand under the raised knee and clasping hands behind the back.',
    },
    benefits: [
      'Stretches the obliques, erector spinae, and multifidus along the entire spine',
      'Improves rotational mobility of the thoracic and lumbar spine',
      'Stimulates the intervertebral discs and promotes spinal fluid circulation',
      'Releases tension in the piriformis and outer hip',
      'Aids digestion by gently massaging the abdominal organs',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-knee-to-chest',
    name: 'Knee-to-Chest',
    difficulty: 'beginner',
    targetMuscles: ['erector spinae', 'gluteus maximus', 'piriformis', 'hip flexors'],
    bodyAreas: ['lower-back', 'hips'],
    illustrationFile: 'back-knee-to-chest.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back on a mat, both knees drawn up to their chest with arms wrapped gently around their shins in a supine hug, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie flat on your back on a mat with legs extended.',
      'Bend both knees and draw them toward your chest.',
      'Interlace your fingers just below your knees, or clasp your shins.',
      'Gently hug your knees in toward your chest without forcing — aim for a comfortable, firm pull.',
      'Press your lower back into the floor as you hold, flattening the lumbar curve.',
      'Keep your head, neck, and shoulders relaxed on the mat.',
      'For a gentle rocking variation, slowly rock side to side to massage the lower back.',
      'To intensify one side, extend one leg long and draw only one knee in, repeating on both sides.',
    ],
    tips: [
      'Hold below the knee joint, never on top of the kneecap, to avoid joint stress.',
      'Relax your shoulders and jaw — this is a restorative stretch, not an effort.',
      'If you have tight hamstrings, keep the extended leg slightly bent.',
      'Press your tailbone gently toward the floor to maximize the lower back stretch.',
      'Breathe into your lower belly — the rise and fall will create a gentle internal massage.',
    ],
    modifications: {
      easier: 'Draw only one knee at a time to your chest, keeping the other leg extended flat on the floor.',
      harder: 'Add a gentle chin tuck, lifting your forehead toward your knees to also stretch the thoracic spine.',
    },
    benefits: [
      'Directly decompresses the lumbar spine and sacroiliac joints',
      'Stretches the erector spinae and gluteus maximus',
      'Relieves tension from prolonged sitting or standing',
      'Gently stretches the piriformis and hip rotators',
      'Reduces lower back discomfort by flattening the lumbar curve',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-pelvic-tilt',
    name: 'Pelvic Tilt',
    difficulty: 'beginner',
    targetMuscles: ['rectus abdominis', 'erector spinae', 'gluteus maximus', 'transverse abdominis'],
    bodyAreas: ['lower-back'],
    illustrationFile: 'back-pelvic-tilt.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back with knees bent and feet flat on the floor, gently pressing their lower back into the mat with a subtle pelvic tilt, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your back with your knees bent, feet flat on the floor hip-width apart.',
      'Notice the natural arch in your lower back — there should be a small gap between your back and the floor.',
      'Gently engage your abdominals and tighten your glutes.',
      'Slowly tilt your pelvis backward, pressing your lower back flat against the floor.',
      'Hold this position for the duration, breathing normally throughout.',
      'You should feel a mild contraction in your abdominals and a gentle stretch in your lower back.',
      'Release slowly and allow the natural lumbar curve to return.',
      'Repeat for 10–15 repetitions, or hold continuously for the set duration.',
    ],
    tips: [
      'This is a subtle movement — do not bridge your hips off the floor.',
      'Think of trying to flatten a wrinkle out of your shirt on your lower back against the floor.',
      'Engage your core before you tilt — this protects the spine and activates deep stabilizers.',
      'Keep your ribcage down and avoid flaring it as you tilt the pelvis.',
      'Breathe out as you press the back into the floor to engage the transverse abdominis.',
    ],
    modifications: {
      easier: 'Perform standing against a wall — press your lower back into the wall without squatting.',
      harder: 'Hold the tilt while extending one leg to a hover, maintaining spinal contact with the floor throughout.',
    },
    benefits: [
      'Strengthens and activates the deep core stabilizers including the transverse abdominis',
      'Stretches and mobilizes the lumbar erector spinae',
      'Reduces anterior pelvic tilt which is a common cause of lower back pain',
      'Trains the neuromuscular pattern for neutral spine awareness',
      'Prepares the lower back for more demanding movements',
    ],
    defaultHoldSeconds: 20,
  },
  {
    id: 'back-sphinx-pose',
    name: 'Sphinx Pose',
    difficulty: 'beginner',
    targetMuscles: ['erector spinae', 'gluteus maximus', 'rectus abdominis', 'chest'],
    bodyAreas: ['lower-back', 'upper-back', 'chest'],
    illustrationFile: 'back-sphinx-pose.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying face down with forearms on the floor, elbows under shoulders, chest lifted and gaze forward in sphinx pose, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie face down on your mat with your legs extended, tops of your feet flat on the floor.',
      'Place your forearms on the floor, elbows directly beneath your shoulders.',
      'Press your forearms and hands firmly into the floor.',
      'Inhale and gently lift your chest and head off the floor, straightening the upper back.',
      'Your pelvis and lower body should remain on the floor.',
      'Draw your shoulder blades gently together and down away from your ears.',
      'Gaze forward and slightly upward, keeping the neck long and aligned.',
      'Hold while breathing steadily, feeling a gentle extension through the lumbar spine.',
    ],
    tips: [
      'Keep your elbows directly under your shoulders — if they drift forward, the stretch is lost.',
      'Actively press the pubic bone into the floor to protect the lower back from over-arching.',
      'Squeeze your legs together gently and press the tops of your feet down for lower body stability.',
      'Think of lifting through the sternum rather than crunching the back of your neck.',
      'If you feel any sharp pain in your lower back, lower down slightly or stop completely.',
    ],
    modifications: {
      easier: 'Prop a thin pillow under your hips to reduce the lumbar extension.',
      harder: 'Lift your elbows off the floor briefly, resting on just your hands for a deeper backbend (Cobra entry).',
    },
    benefits: [
      'Gently extends and strengthens the lumbar erector spinae',
      'Counteracts the effects of prolonged forward flexion from sitting and desk work',
      'Opens the chest and stretches the anterior abdominals',
      'Stimulates the kidneys and abdominal organs through gentle compression',
      'Relieves disc-related lower back pain by encouraging anterior positioning',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-cobra-pose',
    name: 'Cobra Pose',
    difficulty: 'intermediate',
    targetMuscles: ['erector spinae', 'gluteus maximus', 'rectus abdominis', 'pectoralis major', 'serratus anterior'],
    bodyAreas: ['lower-back', 'upper-back', 'chest'],
    illustrationFile: 'back-cobra-pose.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying face down with arms extended pressing their chest up off the floor into cobra pose, lower body remaining on the mat, elbows slightly bent, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie face down on your mat with your legs hip-width apart and tops of feet pressing into the floor.',
      'Place your hands flat on the floor beneath your shoulders, fingers spread wide.',
      'Draw your elbows close to your ribs and slightly back.',
      'Press the tops of your feet and pelvis firmly into the floor.',
      'Inhale and begin to slowly straighten your arms, lifting your chest and abdomen off the floor.',
      'Only straighten your arms as far as your lower back allows without discomfort — a slight bend in the elbows is fine.',
      'Roll your shoulders back and down, opening the chest and lifting the sternum.',
      'Keep your gaze forward and slightly upward, chin tucked just enough to keep the neck long.',
      'Hold, breathing steadily, then exhale as you slowly lower back to the floor.',
    ],
    tips: [
      'Never use your arm strength to force height — let your back muscles do the lifting.',
      'Keep a micro-bend in your elbows to ensure your back muscles remain engaged.',
      'Actively squeeze your inner thighs toward each other and press all ten toenails into the mat.',
      'If your lower back compresses painfully, lower your chest slightly or return to Sphinx Pose.',
      'Broaden across your collarbones at the top of the movement for maximum chest opening.',
    ],
    modifications: {
      easier: 'Perform Sphinx Pose with forearms on the floor instead of pushing all the way up.',
      harder: 'Lift one leg off the floor while in full Cobra to increase erector spinae engagement on one side.',
    },
    benefits: [
      'Actively strengthens the erector spinae and multifidus through an extended range',
      'Stretches the rectus abdominis, hip flexors, and pectoralis major simultaneously',
      'Counteracts kyphotic posture from desk work and prolonged sitting',
      'Encourages healthy extension in all spinal segments',
      'Improves upper back and shoulder mobility',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-thoracic-rotation',
    name: 'Thoracic Rotation',
    difficulty: 'intermediate',
    targetMuscles: ['rhomboids', 'middle trapezius', 'erector spinae', 'obliques', 'multifidus'],
    bodyAreas: ['upper-back'],
    illustrationFile: 'back-thoracic-rotation.png',
    illustrationPrompt:
      'Flat vector illustration of a person on hands and knees with one hand placed behind their head, rotating their upper torso to open that elbow toward the ceiling in a thoracic rotation stretch, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Start in a tabletop position on hands and knees, wrists under shoulders and knees under hips.',
      'Place your right hand behind your head, elbow pointing out to the side.',
      'Keep your left hand firmly on the floor and your lower body completely still.',
      'Inhale to prepare.',
      'Exhale and rotate your right elbow down and toward your left arm, threading through the gap.',
      'Inhale to return to the starting position.',
      'Exhale and rotate your right elbow up and toward the ceiling, opening your chest fully to the right.',
      'Follow your elbow with your gaze to encourage cervical rotation.',
      'Perform 6–8 repetitions per side, then switch arms.',
    ],
    tips: [
      'The rotation must come from your thoracic spine — lock the lower back and pelvis in place.',
      'Think of your hips as a fixed anchor point that does not move during the rotation.',
      'Move slowly and with control — momentum defeats the purpose of this mobility drill.',
      'Try to reach the ceiling with your elbow at the top of the movement.',
      'Keep the supporting arm straight and actively push the floor away for spinal stability.',
    ],
    modifications: {
      easier: 'Perform seated in a chair with hands clasped behind your head and rotate the torso side to side.',
      harder: 'Add a thread-the-needle hold at the bottom for 5 seconds before rotating back to the ceiling.',
    },
    benefits: [
      'Directly mobilizes the thoracic vertebrae, which are the most commonly restricted spinal segment',
      'Stretches the rhomboids and middle trapezius on the rotating side',
      'Improves rotational mobility for sports and daily activities',
      'Reduces upper back stiffness caused by forward head posture',
      'Restores functional coupling between thoracic and cervical rotation',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-prayer-stretch',
    name: 'Prayer Stretch',
    difficulty: 'beginner',
    targetMuscles: ['latissimus dorsi', 'teres major', 'erector spinae', 'trapezius'],
    bodyAreas: ['upper-back', 'lower-back', 'shoulders'],
    illustrationFile: 'back-prayer-stretch.png',
    illustrationPrompt:
      'Flat vector illustration of a person kneeling in front of a chair or low surface, arms extended forward with palms down and forehead resting on their arms in a prayer stretch position, hips sitting back toward heels, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Kneel on the floor in front of a low table, chair seat, or exercise ball.',
      'Place both hands on the surface with arms fully extended, shoulder-width apart.',
      'Slowly sit your hips back toward your heels while keeping your arms extended and hands in place.',
      'Allow your chest to drop toward the floor, creating a long diagonal line from hips to hands.',
      'Rest your forehead on your arms or the surface if comfortable.',
      'Actively press your palms down and stretch your fingers forward to increase the pull through your lats.',
      'Hold while breathing into your back, feeling the stretch spread from your armpits down your sides.',
      'To release, walk your hands back toward your body and return to seated.',
    ],
    tips: [
      'The further you sit your hips back, the more you will feel the stretch in the lats and lower back.',
      'Keep your arms straight throughout — bending the elbows reduces the stretch significantly.',
      'If your hips cannot reach your heels, place a pillow between your thighs and calves.',
      'Let your head drop completely to release any tension held in the neck and upper traps.',
      'Try tilting your hands slightly to one side to bias the stretch toward one lat at a time.',
    ],
    modifications: {
      easier: 'Perform standing with hands on a wall at waist height, stepping feet back until hips are over ankles.',
      harder: 'Clasp hands and turn them palm-out to add a wrist flexor and forearm stretch to the position.',
    },
    benefits: [
      'Provides one of the most effective stretches for the latissimus dorsi and teres major',
      'Decompresses the entire spine through a long-axis traction effect',
      'Stretches the middle and lower trapezius and rhomboids',
      'Reduces tightness in the thoracolumbar fascia',
      'Improves shoulder flexion range of motion as a secondary benefit',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'back-standing-back-extension',
    name: 'Standing Back Extension',
    difficulty: 'beginner',
    targetMuscles: ['erector spinae', 'gluteus maximus', 'rectus abdominis', 'hip flexors'],
    bodyAreas: ['lower-back', 'upper-back'],
    illustrationFile: 'back-standing-back-extension.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing upright with hands placed on their lower back, gently leaning backward into a standing backbend to stretch the spine, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet hip-width apart, toes pointing forward.',
      'Place the heels of both hands on your lower back, fingers pointing downward.',
      'Engage your abdominals gently to create spinal support.',
      'Inhale and grow tall through the crown of your head.',
      'Exhale and slowly lean backward, using your hands as a gentle supportive guide.',
      'Look upward as you extend, letting the backbend distribute evenly through the spine.',
      'Go only as far as feels comfortable — this should be a pleasant stretch, not pain.',
      'Hold briefly, then inhale as you return to upright, using your core to control the return.',
    ],
    tips: [
      'Bend the knees slightly if you feel any pinching or compression in your lower back.',
      'Do not jam the extension into one spot — try to feel it spread across the whole spine.',
      'Keep your glutes slightly engaged to protect the sacroiliac joints.',
      'Look up gently rather than dropping your head all the way back to avoid neck strain.',
      'This is ideal as a reset after prolonged forward flexion — do it every 30–45 minutes at a desk.',
    ],
    modifications: {
      easier: 'Perform with a slight knee bend and limit the range to just a few degrees of extension.',
      harder: 'Raise arms overhead before extending backward, increasing the lever arm and stretch through the trunk.',
    },
    benefits: [
      'Directly counteracts lumbar flexion fatigue from sitting and forward bending',
      'Activates and wakes up the erector spinae and multifidus',
      'Stretches the rectus abdominis and hip flexors',
      'Can relieve acute lower back stiffness quickly as a movement snack',
      'Improves lumbar extension mobility which declines with sedentary behavior',
    ],
    defaultHoldSeconds: 20,
  },
];
