import { Exercise } from '../types';

export const chestExercises: Exercise[] = [
  {
    id: 'chest-doorway-stretch',
    name: 'Doorway Chest Stretch',
    difficulty: 'beginner',
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid', 'coracobrachialis'],
    bodyAreas: ['chest', 'shoulders'],
    illustrationFile: 'chest-doorway-stretch.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing in a doorway with both arms raised to 90 degrees and forearms resting against the door frame, leaning their chest gently forward through the opening in a doorway chest stretch, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand in the center of a doorway facing through it.',
      'Raise both arms to 90 degrees — upper arms parallel to the floor, forearms pointing straight up.',
      'Place your forearms and palms flat against the door frame on each side.',
      'Step one foot forward through the doorway into a staggered stance.',
      'Gently lean your body weight forward, allowing your chest to pass through the plane of the door frame.',
      'You should feel a strong stretch across the front of your chest and the fronts of your shoulders.',
      'Keep your chin slightly tucked and avoid letting your lower back hyperextend.',
      'Hold, breathing into your chest, then step back to release.',
    ],
    tips: [
      'Experiment with arm height — lower arms (below 90°) bias the lower pec, higher arms target the upper pec.',
      'Do not shrug your shoulders up toward your ears; actively keep them pulled down and back.',
      'The stretch intensity is controlled by how far forward you lean — start conservatively.',
      'Keep your core engaged to prevent your lower back from arching excessively.',
      'If one side is tighter, spend a few extra seconds leaning slightly toward the tighter side.',
    ],
    modifications: {
      easier: 'Place hands against a wall corner instead and lean in just slightly, reducing the range of stretch.',
      harder: 'Place one arm at a time on the frame and rotate your torso away from that arm for a unilateral deep stretch.',
    },
    benefits: [
      'Stretches the pectoralis major and minor across their full length',
      'Counteracts the rounded shoulder posture created by prolonged sitting and keyboard use',
      'Improves shoulder horizontal abduction range of motion',
      'Reduces anterior shoulder tension that contributes to neck and upper back pain',
      'Opens the chest to support improved breathing mechanics',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'chest-floor-opener',
    name: 'Floor Chest Opener',
    difficulty: 'beginner',
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid', 'biceps brachii'],
    bodyAreas: ['chest', 'shoulders'],
    illustrationFile: 'chest-floor-opener.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back on a mat with arms extended out to the sides like a T shape at shoulder height, palms facing up, chest open and relaxed toward the ceiling in a supine chest opener, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie flat on your back on a mat with legs extended or knees bent, whichever is more comfortable.',
      'Extend both arms out to your sides like a T, at shoulder height, with palms facing up.',
      'Allow gravity to gently pull your shoulders toward the floor, opening the front of your chest.',
      'If your shoulders do not reach the floor comfortably, place a folded blanket under each arm.',
      'Relax your jaw, neck, and entire upper body — this is a completely passive stretch.',
      'Breathe slowly and deeply, feeling your chest broaden with each inhale.',
      'With each exhale, allow a little more tension to release from the front of your shoulders.',
      'To increase the stretch, bend your elbows to 90 degrees (goalpost position) and allow them to lower toward the floor.',
    ],
    tips: [
      'Do not force your arms down — let gravity do all the work over time.',
      'Keep your lower back in contact with the floor to avoid compensating through lumbar extension.',
      'The goalpost variation targets the upper pec more effectively than the straight-arm version.',
      'Closing your eyes and focusing on breath will help the nervous system allow a deeper release.',
      'If you feel tingling in your hands, raise your arms slightly to reduce stretch on the brachial plexus.',
    ],
    modifications: {
      easier: 'Place a folded blanket or yoga block under each forearm to reduce the range of shoulder extension.',
      harder: 'Hold a light weight in each hand to add gentle passive traction and deepen the shoulder stretch.',
    },
    benefits: [
      'Passively lengthens the pectoralis major and minor through gravity-assisted stretching',
      'Stretches the anterior deltoid and biceps brachii long head',
      'Relieves tension accumulated in the chest from forward-rounded posture',
      'Promotes diaphragmatic breathing by opening the anterior ribcage',
      'Calms the nervous system — combining chest opening with relaxation reduces stress hormones',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'chest-clasp-behind-back',
    name: 'Clasp Behind Back',
    difficulty: 'beginner',
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid', 'subscapularis', 'rhomboids'],
    bodyAreas: ['chest', 'shoulders', 'upper-back'],
    illustrationFile: 'chest-clasp-behind-back.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing tall with their hands clasped together behind their back, arms extended and slightly lifted, chest open and shoulders pulled back in a standing chest clasp stretch, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet hip-width apart and your spine in a neutral, upright position.',
      'Reach both arms behind your back and interlace your fingers together.',
      'If your hands cannot meet, hold opposite wrists or use a strap or towel.',
      'Inhale and straighten your arms, pressing your knuckles gently toward the floor.',
      'Squeeze your shoulder blades together and draw them down your back.',
      'Lift your chest upward and open, while keeping your chin level and neck long.',
      'For a deeper stretch, hinge slightly forward at the hips and lift your clasped hands toward the ceiling.',
      'Hold while breathing expansively into your chest, then release on an exhale.',
    ],
    tips: [
      'Focus on squeezing the shoulder blades together — this is what drives the chest opening.',
      'Avoid jutting your chin forward or compressing the back of the neck.',
      'If using a strap, gripping it closer together will increase the stretch intensity.',
      'Keep a slight bend in your knees if you feel strain in your lower back during the forward hinge.',
      'This stretch is effective as a posture reset — do it against a wall for better vertical feedback.',
    ],
    modifications: {
      easier: 'Instead of clasping, simply pull your shoulders back and hold a neutral retracted position.',
      harder: 'Hinge fully forward at the hips so your torso is parallel to the floor and raise hands as high as possible.',
    },
    benefits: [
      'Stretches the pectoralis major and minor through shoulder extension and retraction',
      'Activates and strengthens the rhomboids and middle trapezius as antagonists',
      'Improves shoulder extension range of motion',
      'Directly corrects rounded shoulder posture by reinforcing scapular retraction',
      'Can be done anywhere, making it an ideal postural correction exercise',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'chest-wall-stretch',
    name: 'Wall Chest Stretch',
    difficulty: 'beginner',
    targetMuscles: ['pectoralis major', 'anterior deltoid', 'coracobrachialis', 'biceps brachii'],
    bodyAreas: ['chest', 'shoulders'],
    illustrationFile: 'chest-wall-stretch.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing sideways next to a wall with one arm extended behind them pressing their palm flat against the wall at shoulder height, rotating their torso away from the wall to stretch their chest, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand sideways next to a wall, about one arm-length away from it.',
      'Extend your right arm behind you and place your palm flat on the wall at shoulder height.',
      'Keep your arm straight with a soft elbow.',
      'Gently rotate your entire torso to the left, turning away from your planted hand.',
      'Step your left foot forward if needed to allow a fuller rotation.',
      'You should feel an immediate stretch across the right pectoral and front of the right shoulder.',
      'Hold while breathing slowly, allowing the stretch to deepen with each exhale.',
      'Slowly rotate back to release, then switch sides.',
    ],
    tips: [
      'The arm height changes which part of the pec is targeted — lower arm hits the sternal (lower) fibers, higher hits the clavicular (upper) fibers.',
      'Perform the stretch at three heights: arm low at 45°, arm at 90°, and arm at 120° to cover all pec fiber angles.',
      'Avoid twisting from your hips — the rotation should come from your thoracic spine and ribcage.',
      'Keep your shoulder blade pulled down and back, not shrugged up toward your ear.',
      'Do not lean away from the wall — stand tall and rotate in place.',
    ],
    modifications: {
      easier: 'Reduce the degree of torso rotation, stopping before any discomfort is felt.',
      harder: 'Add a slight cervical rotation by looking over your free shoulder to increase the stretch through the pec minor and anterior scalene.',
    },
    benefits: [
      'Effectively isolates and stretches the pectoralis major in a standing, load-bearing position',
      'Can be targeted precisely to upper or lower pec fibers through arm height variation',
      'Stretches the anterior deltoid and coracobrachialis',
      'Improves shoulder horizontal abduction flexibility',
      'Requires no equipment and can be performed in any room or office',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'chest-side-lying-rotation',
    name: 'Side-Lying Chest Rotation',
    difficulty: 'intermediate',
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid', 'rhomboids', 'thoracic erector spinae'],
    bodyAreas: ['chest', 'upper-back', 'shoulders'],
    illustrationFile: 'chest-side-lying-rotation.png',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their side on a mat with knees stacked and bent, bottom arm extended forward and top arm rotating open toward the ceiling and floor behind them in a side-lying thoracic rotation, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your right side on a mat with your hips and knees bent to 90 degrees, knees stacked.',
      'Optionally place a pillow between your knees to keep the pelvis level.',
      'Extend both arms forward at shoulder height, one on top of the other, palms together.',
      'Keeping your knees stacked and still, slowly lift your top (left) arm and begin rotating it upward.',
      'Follow your left hand with your gaze as it sweeps up toward the ceiling and then over toward the floor on the opposite side.',
      'Allow your left shoulder to approach the floor behind you, opening your chest to face the ceiling.',
      'Hold at the endpoint, focusing on keeping your knees down rather than chasing the arm with your hips.',
      'Inhale to open further, exhale slowly. Return the arm forward to reset, then repeat for reps or switch sides.',
    ],
    tips: [
      'The knees staying stacked on the floor is the key constraint — if they lift, you have gone too far.',
      'Think of the movement as a book opening and closing, with your spine as the binding.',
      'Move slowly — the stretch comes from the thoracic rotation, which needs time to unlock.',
      'If your shoulder cannot reach the floor, place a folded blanket as a target rather than forcing it.',
      'Keep both arms long and straight to maximize the lever arm and the pectoral stretch.',
    ],
    modifications: {
      easier: 'Reduce the rotation range, stopping when you feel the stretch begin rather than going to full floor touch.',
      harder: 'Hold a light weight in your top hand to add gentle gravity-assisted traction at the end range.',
    },
    benefits: [
      'Combines thoracic rotation mobility with a chest and anterior shoulder stretch',
      'Stretches the pectoralis major and minor while the spine is supported',
      'Improves the coupling of thoracic rotation and shoulder horizontal abduction',
      'Particularly effective for addressing restrictions in the upper thoracic spine',
      'The stacked knee position isolates the stretch to the upper body, protecting the lower back',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'chest-expansion',
    name: 'Chest Expansion',
    difficulty: 'beginner',
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid', 'intercostals', 'serratus anterior'],
    bodyAreas: ['chest', 'shoulders'],
    illustrationFile: 'chest-expansion.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing tall with arms spread wide open to each side and slightly back, palms facing forward, chin slightly lifted and chest expanded broadly in a standing chest expansion stretch, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet hip-width apart in a tall, grounded position.',
      'Let your arms hang naturally at your sides.',
      'Inhale slowly and deeply as you sweep both arms wide open to your sides, rising slightly above shoulder height.',
      'Rotate your palms to face forward and upward as your arms open.',
      'Pull your shoulder blades firmly together as your chest expands and lifts.',
      'Tilt your chin slightly upward to open the front of the throat and deepen the chest expansion.',
      'Hold at the peak of your inhale, feeling the front of your chest fully broadened.',
      'Exhale slowly and let your arms float back down, returning to the starting position.',
      'Repeat with breath for 5–8 cycles, or hold the expanded position statically for the full duration.',
    ],
    tips: [
      'Synchronize the arm movement precisely with your breath — the inhale drives the opening.',
      'At the top, actively retract the shoulder blades as hard as comfortably possible.',
      'Keep the movement slow and controlled — rushing prevents the intercostals from fully expanding.',
      'Imagine you are trying to make your chest as wide as possible, not just lifting your arms.',
      'This is an excellent breath-work pairing — use it during mindfulness or meditation practice.',
    ],
    modifications: {
      easier: 'Keep arms at or below shoulder height and focus purely on the breathing expansion component.',
      harder: 'Hold light dumbbells in each hand as you open the arms to increase the shoulder stabilizer recruitment.',
    },
    benefits: [
      'Stretches the pectoralis major, pectoralis minor, and the intercostal muscles simultaneously',
      'Expands the thoracic cavity and increases lung capacity over time',
      'Trains the serratus anterior through the arc of arm movement',
      'Encourages diaphragmatic breathing and corrects shallow chest-only breathing patterns',
      'Combines postural correction with mindful breathing, making it effective for stress and fatigue',
    ],
    defaultHoldSeconds: 30,
  },
];
