import { Exercise } from '../types';

export const fullBodyExercises: Exercise[] = [
  {
    id: 'full-body-upward-salute',
    name: 'Upward Salute',
    difficulty: 'beginner',
    targetMuscles: ['rectus abdominis', 'intercostals', 'latissimus dorsi', 'deltoids', 'quadriceps'],
    bodyAreas: ['full-body', 'shoulders', 'chest'],
    illustrationFile: 'full-body-upward-salute.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing tall with arms raised straight overhead, palms facing each other and fingertips pointing to the sky, feet together, slight backbend, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet together or hip-width apart, arms resting at your sides.',
      'On an inhale, sweep both arms out to the sides and then up overhead.',
      'Press your palms together or keep them shoulder-width apart with fingers pointing toward the ceiling.',
      'Gently draw your shoulder blades down your back to avoid shrugging.',
      'Engage your core and lengthen through your entire spine.',
      'If comfortable, tilt your head back slightly and gaze up at your thumbs.',
      'Hold the position, breathing deeply into your chest and ribcage.',
      'To release, exhale and lower your arms back down to your sides.',
    ],
    tips: [
      'Press all four corners of your feet evenly into the floor to stay grounded.',
      'Avoid letting your lower back collapse — engage your abs to support the backbend.',
      'Keep your arms active by imagining you are reaching your fingertips toward the ceiling.',
      'If your shoulders are tight, keep a slight bend in your elbows rather than forcing straight arms.',
    ],
    modifications: {
      easier: 'Keep hands shoulder-width apart instead of pressing palms together, or keep a soft bend at the elbows to reduce shoulder strain.',
      harder: 'Rise up onto the balls of your feet as you lift your arms to add a balance challenge and engage the calves.',
    },
    benefits: [
      'Stretches the sides of the torso, intercostals, and latissimus dorsi',
      'Opens the chest and expands lung capacity',
      'Lengthens the spine and improves posture',
      'Activates the core and stabilizing muscles along the entire back',
      'Energizes the body and improves focus at the start of a practice',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-downward-dog',
    name: 'Downward Dog',
    difficulty: 'intermediate',
    targetMuscles: ['hamstrings', 'calves', 'gastrocnemius', 'deltoids', 'triceps', 'latissimus dorsi', 'thoracic spine extensors'],
    bodyAreas: ['full-body', 'hamstrings', 'calves', 'shoulders', 'upper-back', 'lower-back'],
    illustrationFile: 'full-body-downward-dog.png',
    illustrationPrompt:
      'Flat vector illustration of a person in downward facing dog yoga pose forming an inverted V shape, hands flat on the ground shoulder-width apart, hips raised high, heels pressing toward the floor, spine long, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Begin on all fours with your wrists directly under your shoulders and knees under your hips.',
      'Spread your fingers wide and press firmly through all ten fingertips and the base of each finger.',
      'Tuck your toes under and, on an exhale, lift your knees off the floor.',
      'Straighten your legs as much as your hamstrings allow and drive your hips up and back toward the ceiling.',
      'Work to create a straight line from your wrists through to your hips, forming an inverted V shape.',
      'Press your heels toward the floor — they do not need to touch down completely.',
      'Let your head hang naturally between your upper arms with your ears in line with your biceps.',
      'Hold, breathing steadily, then lower your knees back to the floor to release.',
    ],
    tips: [
      'Externally rotate your upper arms slightly so your elbow creases face forward — this protects your shoulder joints.',
      'Push the floor away rather than just lifting your hips; the arm push is what decompresses the spine.',
      'Keep a micro-bend in your knees if your hamstrings are tight — forcing straight legs will round your lower back.',
      'Distribute weight evenly between hands and feet; avoid dumping into the wrists.',
    ],
    modifications: {
      easier: 'Keep a generous bend in both knees to take the emphasis off tight hamstrings and focus on lengthening the spine instead.',
      harder: 'Lift one leg straight up toward the ceiling (Three-Legged Dog) to deepen the hip flexor stretch and add core stability work.',
    },
    benefits: [
      'Lengthens the hamstrings, calves, and Achilles tendons',
      'Decompresses the lumbar spine and releases tension in the lower back',
      'Strengthens the shoulders, triceps, and wrists',
      'Opens the thoracic spine and improves upper-back mobility',
      'Provides a mild inversion that promotes circulation and calms the nervous system',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-upward-dog',
    name: 'Upward Dog',
    difficulty: 'intermediate',
    targetMuscles: ['rectus abdominis', 'hip flexors', 'psoas', 'pectorals', 'intercostals', 'triceps', 'erector spinae'],
    bodyAreas: ['full-body', 'chest', 'lower-back', 'hips'],
    illustrationFile: 'full-body-upward-dog.png',
    illustrationPrompt:
      'Flat vector illustration of a person in upward facing dog yoga pose lying prone with arms straight, chest lifted high off the floor, thighs hovering above the ground, tops of feet pressing down, gaze forward, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie face down on your mat with your legs extended behind you, tops of your feet flat on the floor.',
      'Place your palms flat on the floor beside your lower ribs, fingers pointing forward.',
      'On an inhale, press firmly through your palms and straighten your arms fully.',
      'Lift your chest, upper abdomen, and thighs completely off the floor — only your hands and the tops of your feet make contact.',
      'Draw your shoulders down and back, away from your ears, and roll your collarbones open.',
      'Gently squeeze your glutes to protect your lower back and lengthen your tailbone toward your heels.',
      'Gaze forward or very slightly upward — avoid crunching the back of your neck.',
      'Hold, then slowly lower back down on an exhale.',
    ],
    tips: [
      'The key distinction from Cobra is that your thighs must hover off the floor — do not let them rest down.',
      'Press through the knuckles of your index fingers to prevent the wrists from rolling outward.',
      'If your lower back feels compressed, squeeze your glutes and lengthen your tailbone rather than just bending more.',
      'Keep your elbows slightly soft rather than hyperextended if you are hypermobile.',
    ],
    modifications: {
      easier: 'Practice Cobra Pose instead — keep your pelvis on the floor and only partially straighten your arms to reduce the backbend intensity.',
      harder: 'Hold the peak position for an extra breath and then slowly lower with control, treating the descent as a strength exercise for the arms and core.',
    },
    benefits: [
      'Stretches the hip flexors, psoas, and abdominals',
      'Opens the chest and anterior shoulder capsule',
      'Strengthens the triceps, wrists, and spinal extensors',
      'Counteracts the forward-flexed posture of prolonged sitting',
      'Stimulates the digestive organs through abdominal compression during the release',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-standing-side-bend',
    name: 'Standing Side Bend',
    difficulty: 'beginner',
    targetMuscles: ['intercostals', 'quadratus lumborum', 'latissimus dorsi', 'obliques', 'deltoids'],
    bodyAreas: ['full-body', 'upper-back', 'lower-back', 'shoulders'],
    illustrationFile: 'full-body-standing-side-bend.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing upright bending smoothly to the right with right arm reaching up and over the head and left hand resting on the left thigh, creating a graceful C-curve through the torso, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet hip-width apart and your arms hanging at your sides.',
      'Root down through both feet and engage your core gently to stabilize your hips.',
      'On an inhale, sweep your right arm up overhead and keep it alongside your right ear.',
      'On an exhale, begin to lean your torso smoothly to the left, drawing a long arc with your right fingertips.',
      'Rest your left hand lightly on your left thigh for support — avoid pushing or pulling on your leg.',
      'Keep both hips level and square to the front; do not let your pelvis shift to the right.',
      'Breathe into the right side of your ribcage, feeling it expand with each inhale.',
      'On an inhale, engage your core to return to center, then exhale and lower your arm. Repeat on the other side.',
    ],
    tips: [
      'Think of reaching long rather than bending sharply — length comes first, then the lean.',
      'Keep both feet firmly planted to prevent the hips from sliding out to the opposite side.',
      'Your gaze can stay forward or look up toward your raised hand, whichever is comfortable for your neck.',
      'If balance is challenging, stand with your back against a wall for extra support.',
    ],
    modifications: {
      easier: 'Place your top hand on the back of your head instead of reaching overhead to reduce the load on the shoulder and shorten the lever arm.',
      harder: 'Clasp both hands overhead and bend as a unit, or try the pose with your feet together to increase the balance challenge.',
    },
    benefits: [
      'Stretches the intercostal muscles and expands breathing capacity',
      'Lengthens the quadratus lumborum, a common source of lower-back tightness',
      'Mobilizes the lateral spine and thoracic cage',
      'Stretches the latissimus dorsi and the entire lateral fascial line',
      'Improves lateral flexion range of motion lost from prolonged seated postures',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    difficulty: 'expert',
    targetMuscles: ['hip flexors', 'psoas', 'hamstrings', 'glutes', 'thoracic rotators', 'adductors', 'pectorals', 'ankle dorsiflexors'],
    bodyAreas: ['full-body', 'hips', 'hamstrings', 'upper-back', 'chest', 'lower-back'],
    illustrationFile: 'full-body-worlds-greatest-stretch.png',
    illustrationPrompt:
      'Flat vector illustration of a person in a deep lunge position with the front foot flat, front hand on the ground inside the front foot, and the opposite arm reaching straight up to the sky in a thoracic rotation, torso twisting open, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Begin in a high plank position with your core engaged and body in a straight line.',
      'Step your right foot forward to land just outside your right hand, coming into a low lunge.',
      'Lower your left knee gently to the floor (or keep it hovering for greater intensity).',
      'Place your right elbow down to the floor inside your right foot — you should feel a deep stretch in the right hip flexor and groin.',
      'From here, rotate your thoracic spine by sweeping your right arm up toward the ceiling, following it with your gaze.',
      'Hold the rotation at its end range, breathing into the stretch for two or three full breaths.',
      'Return your right hand to the floor, then step back to plank.',
      'Repeat on the left side by stepping the left foot forward. Complete two to three slow cycles per side.',
    ],
    tips: [
      'Drive your front knee toward your little toe to keep the hip open rather than collapsing inward.',
      'The thoracic rotation is the most important part — prioritize rotating your upper back, not just the shoulder.',
      'Keep your back heel in line with your back hip; avoid splaying the back leg out to the side.',
      'Move deliberately through each phase — this stretch rewards slow, controlled movement.',
    ],
    modifications: {
      easier: 'Lower your back knee to the floor throughout the entire stretch to reduce the demand on hip flexor strength and balance.',
      harder: 'Keep the back knee off the floor for the entire sequence and add a hamstring reach at the end by straightening the front leg and hinging the hips back.',
    },
    benefits: [
      'Simultaneously stretches the hip flexors, groin, and adductors of the back leg',
      'Mobilizes the thoracic spine in rotation, a range of motion critical for sport and daily movement',
      'Opens the chest and anterior shoulder of the rotating arm',
      'Improves ankle dorsiflexion and overall hip mobility',
      'Trains the body to coordinate multi-joint movement patterns, making it ideal as a warm-up for athletic activity',
    ],
    defaultHoldSeconds: 45,
  },
  {
    id: 'full-body-lunge-with-twist',
    name: 'Lunge with Twist',
    difficulty: 'intermediate',
    targetMuscles: ['hip flexors', 'psoas', 'quadriceps', 'thoracic rotators', 'obliques', 'glutes'],
    bodyAreas: ['full-body', 'hips', 'quadriceps', 'upper-back', 'lower-back'],
    illustrationFile: 'full-body-lunge-with-twist.png',
    illustrationPrompt:
      'Flat vector illustration of a person in a standing lunge with the right foot forward, both arms extended horizontally with the torso rotating to face the right over the front leg, head following the rotation, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand tall with your feet hip-width apart.',
      'Step your right foot forward into a lunge, lowering your left knee toward the floor or keeping both legs straight in a long stride.',
      'Distribute your weight evenly and make sure your right knee stays directly over your right ankle.',
      'Bring both arms out to shoulder height with palms facing down, forming a T shape.',
      'On an exhale, rotate your entire torso to the right, leading with your chest and following with your gaze.',
      'Keep your hips squared forward as best you can — the rotation comes from your thoracic spine, not your pelvis.',
      'Hold the twist, inhale to lengthen, then exhale to deepen the rotation slightly.',
      'Unwind on an inhale, return to center, and step back to standing. Repeat on the left side.',
    ],
    tips: [
      'Press your front heel firmly into the floor to stabilize the lunge before initiating the twist.',
      'Think about rotating your breastbone toward the ceiling rather than just moving your arms — this engages the thoracic rotation more effectively.',
      'Avoid letting your front knee collapse inward during the twist; it should track over the second toe.',
      'Start with a smaller rotation range and deepen as your body warms up.',
    ],
    modifications: {
      easier: 'Lower your back knee to the floor to create a stable base before attempting the rotation.',
      harder: 'Place your hands in prayer position at your chest and hook your top elbow outside your front thigh to use it as a lever for a deeper rotation.',
    },
    benefits: [
      'Stretches the hip flexors, psoas, and quadriceps of the back leg',
      'Mobilizes the thoracic spine in rotation, improving spinal health and posture',
      'Strengthens the quadriceps and glutes of the front leg',
      'Activates the obliques and deep abdominal stabilizers',
      'Improves overall rotational mobility needed for activities like golf, tennis, and running',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-rag-doll',
    name: 'Rag Doll',
    difficulty: 'beginner',
    targetMuscles: ['hamstrings', 'gluteus maximus', 'erector spinae', 'rhomboids', 'trapezius', 'cervical extensors'],
    bodyAreas: ['full-body', 'hamstrings', 'lower-back', 'upper-back'],
    illustrationFile: 'full-body-rag-doll.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing with feet hip-width apart folded completely forward at the hips, knees slightly bent, arms dangling loosely toward the floor with each hand holding the opposite elbow, head and neck fully relaxed hanging down, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet hip-width apart and a gentle bend in your knees.',
      'On an exhale, hinge forward at your hips and let your upper body fold down toward the floor.',
      'Allow your head, neck, and arms to hang completely freely — release all tension in your upper body.',
      'Grasp each elbow with the opposite hand to create a relaxed frame for your arms.',
      'Let gravity do the work; do not actively pull yourself down or try to straighten your legs.',
      'Gently sway side to side or nod your head yes and no to release any remaining neck tension.',
      'With each exhale, allow yourself to soften a little more toward the floor.',
      'To come up, slowly release your arms, place your hands on your thighs, engage your core, and roll up one vertebra at a time.',
    ],
    tips: [
      'Keep a soft bend in your knees to protect the hamstrings and lower back, especially if you are tight.',
      'The goal is relaxation and release, not touching the floor — let your body hang passively.',
      'Breathe slowly and deeply into your lower back to encourage the muscles to release.',
      'Roll up slowly to avoid a head rush; pause in a halfway-up position if needed.',
    ],
    modifications: {
      easier: 'Place your hands on a chair seat or yoga blocks to shorten the distance to the floor and reduce the hamstring stretch.',
      harder: 'Gradually straighten your legs a little more each hold as your hamstrings warm up, eventually working toward straight legs with the chest pressed toward the thighs.',
    },
    benefits: [
      'Passively lengthens the hamstrings and gluteus maximus',
      'Decompresses the lumbar spine by removing the vertical load of gravity',
      'Releases the erector spinae and rhomboids through passive hanging',
      'Relieves tension in the neck and upper trapezius',
      'Promotes parasympathetic nervous system activation, reducing stress and calming the mind',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'full-body-star-stretch',
    name: 'Star Stretch',
    difficulty: 'beginner',
    targetMuscles: ['inner thighs', 'adductors', 'hamstrings', 'hip abductors', 'latissimus dorsi', 'intercostals', 'deltoids'],
    bodyAreas: ['full-body', 'hips', 'hamstrings', 'shoulders', 'chest'],
    illustrationFile: 'full-body-star-stretch.png',
    illustrationPrompt:
      'Flat vector illustration of a person standing with legs wide apart and both arms stretched straight out to the sides at shoulder height, forming a wide five-pointed star shape with their body, head upright, gaze forward, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Step your feet wide apart — roughly three to four feet, depending on your height.',
      'Turn your toes out slightly, about 30 to 45 degrees, to open through the hips and inner thighs.',
      'Extend both arms out to the sides at shoulder height, palms facing down.',
      'Lengthen through your fingertips in both directions as if someone is pulling your hands apart.',
      'Stand tall, lifting through the crown of your head and gently drawing your shoulder blades down your back.',
      'Press all four corners of each foot into the floor to feel stable and grounded.',
      'Breathe fully and evenly, feeling the expansion across your chest and sides with each inhale.',
      'To release, step your feet back together and lower your arms.',
    ],
    tips: [
      'Avoid locking your knees — keep them very slightly soft to protect the joint.',
      'Imagine a string pulling the top of your head toward the ceiling to maintain length in the spine.',
      'Keep your core lightly engaged so your lower back does not arch excessively.',
      'This is a great transitional stretch — hold it as a reset between more demanding exercises.',
    ],
    modifications: {
      easier: 'Take a narrower stance and reduce the arm reach if the wide-leg position feels unstable.',
      harder: 'Add a side reach by tilting your torso to the right while your left arm arcs up and over, then switch sides, turning the hold into a dynamic lateral flow.',
    },
    benefits: [
      'Opens the inner thighs and adductors through a wide-stance load',
      'Stretches the hip abductors and iliotibial band through the lateral leg line',
      'Expands the chest and stretches the anterior deltoids and pectoral muscles',
      'Improves hip abduction range of motion and groin flexibility',
      'Encourages deep lateral breathing by opening the intercostal spaces',
    ],
    defaultHoldSeconds: 30,
  },
];
