import { Exercise } from '../types';

export const hipExercises: Exercise[] = [
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose',
    difficulty: 'intermediate',
    targetMuscles: ['piriformis', 'hip flexors', 'glutes', 'IT band', 'psoas'],
    bodyAreas: ['hips'],
    illustrationFile: 'pigeon-pose.svg',
    illustrationPrompt:
      'Flat vector illustration of a person in pigeon pose on the floor with front leg bent at 90 degrees and back leg extended straight behind, torso upright or folded forward over the front shin, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Start in a tabletop position on hands and knees.',
      'Slide your right knee forward behind your right wrist and let your right ankle come toward your left wrist, forming a roughly 90-degree angle with your shin.',
      'Extend your left leg straight behind you with the top of the foot resting on the floor.',
      'Square your hips toward the front of the mat as much as possible.',
      'Walk your hands forward and lower your torso toward the floor, or stay upright with hands on the mat.',
      'Hold the stretch, breathing deeply into the right hip.',
      'To release, press into your hands and slide the right knee back to tabletop.',
      'Repeat on the opposite side.',
    ],
    tips: [
      'Place a folded blanket or block under the right hip if it does not reach the floor.',
      'Keep your back foot pointed straight back — do not let it sickle outward.',
      'Engage your core lightly to protect the lower back.',
      'Breathe into the outer hip rather than forcing deeper range of motion.',
    ],
    modifications: {
      easier: 'Perform Figure-4 stretch lying on your back to achieve a similar hip opener with less pressure on the knee.',
      harder: 'Walk your hands further forward and lower your forehead to the floor for a deeper forward fold over the front shin.',
    },
    benefits: [
      'Deeply stretches the piriformis and external hip rotators',
      'Releases tension in the hip flexors and psoas',
      'Increases external hip rotation range of motion',
      'Helps relieve sciatic nerve discomfort',
      'Opens the groin and inner thigh',
    ],
    defaultHoldSeconds: 45,
  },
  {
    id: 'hip-flexor-lunge',
    name: 'Hip Flexor Lunge',
    difficulty: 'beginner',
    targetMuscles: ['hip flexors', 'psoas', 'iliacus', 'rectus femoris', 'quadriceps'],
    bodyAreas: ['hips', 'quadriceps'],
    illustrationFile: 'hip-flexor-lunge.svg',
    illustrationPrompt:
      'Flat vector illustration of a person in a low kneeling lunge with the back knee on the floor and the front foot planted flat, torso upright with hands resting on the front thigh, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Start in a high kneeling position on a mat.',
      'Step your right foot forward so your right knee is directly above your right ankle.',
      'Lower your left knee to the mat and point your left foot behind you.',
      'Keep your torso upright with your chest lifted and shoulders back.',
      'Gently drive your hips forward until you feel a stretch in the front of the left hip.',
      'Rest your hands on your right thigh or raise them overhead for a deeper stretch.',
      'Hold, then switch sides.',
    ],
    tips: [
      'Keep your front knee tracking directly over your second toe — do not let it cave inward.',
      'Tuck your pelvis slightly under to maximize the hip flexor stretch and protect the lower back.',
      'Avoid arching your lower back — stay tall through the crown of the head.',
      'Place a folded blanket under your back knee for extra cushioning.',
    ],
    modifications: {
      easier: 'Keep hands on the floor or on a chair for balance support.',
      harder: 'Raise both arms overhead and lean into a gentle side bend away from the back leg.',
    },
    benefits: [
      'Lengthens the psoas and iliacus, which shorten from prolonged sitting',
      'Stretches the rectus femoris (front quadriceps)',
      'Improves hip extension range of motion',
      'Counteracts anterior pelvic tilt',
      'Reduces tension in the lower back',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'figure-4-stretch',
    name: 'Figure-4 Stretch',
    difficulty: 'beginner',
    targetMuscles: ['piriformis', 'glutes', 'external hip rotators'],
    bodyAreas: ['hips'],
    illustrationFile: 'figure-4-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back on the floor with one ankle crossed over the opposite bent knee forming a figure-4 shape, hands interlaced behind the lower thigh pulling the legs toward the chest, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your back with both knees bent and feet flat on the floor.',
      'Cross your right ankle over your left thigh, just above the knee.',
      'Flex your right foot to protect the knee joint.',
      'Interlace your fingers behind your left thigh and gently draw your left leg toward your chest.',
      'Keep your head and shoulders relaxed on the floor.',
      'Feel the stretch in your right outer hip and glute.',
      'Hold, then switch sides.',
    ],
    tips: [
      'Flex the foot of the crossed leg (right foot) — this protects the knee and deepens the hip stretch.',
      'Draw the leg with your hands, not by straining your neck.',
      'If you cannot reach behind your thigh, loop a towel or strap around it.',
      'Keep both shoulders flat against the floor throughout.',
    ],
    modifications: {
      easier: 'Rest your crossed-ankle leg against a wall with your hips close to the baseboard for a gentler stretch.',
      harder: 'Sit up and cross the ankle over the opposite thigh in a seated position (Seated Figure-4) to increase intensity.',
    },
    benefits: [
      'Stretches the piriformis and deep external hip rotators',
      'Relieves tension in the glutes',
      'Helps alleviate sciatic nerve irritation',
      'Accessible for all fitness levels',
      'Reduces hip tightness from sitting or running',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'butterfly-stretch',
    name: 'Butterfly Stretch',
    difficulty: 'beginner',
    targetMuscles: ['inner thighs', 'adductors', 'groin', 'hip flexors'],
    bodyAreas: ['hips'],
    illustrationFile: 'butterfly-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person sitting on the floor with the soles of their feet pressed together and knees falling out to the sides like butterfly wings, sitting tall with hands holding their feet, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Sit on the floor with your legs in front of you.',
      'Bend your knees and bring the soles of your feet together in front of you.',
      'Let your knees fall out to the sides.',
      'Hold your feet or ankles with both hands and sit tall, lengthening through the spine.',
      'Gently press your elbows against your inner thighs to encourage them toward the floor.',
      'Hinge slightly forward from the hips — keep a flat back rather than rounding.',
      'Hold and breathe deeply.',
    ],
    tips: [
      'Sit on a folded blanket to elevate your hips if your lower back rounds excessively.',
      'Do not force your knees down — use gravity and gentle elbow pressure, never bouncing.',
      'Lead with your chest when hinging forward, not your forehead.',
      'The closer your heels are to your groin, the more intense the stretch.',
    ],
    modifications: {
      easier: 'Move your feet further away from your body to reduce the intensity on the inner thighs.',
      harder: 'Fold forward deeply, bringing your chin toward your feet while maintaining a flat back.',
    },
    benefits: [
      'Stretches the adductors and inner thighs',
      'Opens the groin and hip flexors',
      'Improves hip abduction range of motion',
      'Encourages hip external rotation',
      'Promotes relaxation and pelvic floor release',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'happy-baby',
    name: 'Happy Baby',
    difficulty: 'beginner',
    targetMuscles: ['inner groin', 'hip flexors', 'glutes', 'lower back', 'adductors'],
    bodyAreas: ['hips', 'lower-back'],
    illustrationFile: 'happy-baby.svg',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back with both knees drawn toward the chest and feet pointed toward the ceiling, hands gripping the outer edges of their feet with knees wide apart, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your back on a mat.',
      'Exhale and draw both knees toward your chest.',
      'Open your knees wide, slightly wider than your torso.',
      'Reach up and grip the outer edges of your feet, or hook two fingers around each big toe.',
      'Flex your feet and press your heels toward the ceiling.',
      'Gently draw your knees toward your armpits by pulling down on your feet.',
      'Keep your lower back pressed against the floor.',
      'Rock gently side to side for an additional massage effect if desired.',
    ],
    tips: [
      'Keep your tailbone pressing toward the floor — avoid letting your hips lift up.',
      'If you cannot reach your feet, hold your shins or loop a strap around the arches.',
      'Your ankles should stack directly over your knees (shins vertical).',
      'Relax your neck and jaw completely.',
    ],
    modifications: {
      easier: 'Hold the backs of your thighs instead of your feet, or work one leg at a time.',
      harder: 'Slowly extend one leg toward the floor while keeping the other in Happy Baby for a hamstring challenge.',
    },
    benefits: [
      'Gently opens the inner groin and adductors',
      'Releases the lower back and sacrum',
      'Stretches the hip flexors and glutes',
      'Decompresses the lumbar spine',
      'Calming effect on the nervous system',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'frog-stretch',
    name: 'Frog Stretch',
    difficulty: 'intermediate',
    targetMuscles: ['inner thighs', 'adductors', 'groin', 'hip flexors'],
    bodyAreas: ['hips'],
    illustrationFile: 'frog-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person on hands and knees with both knees spread wide to the sides and feet turned out behind them, hips sinking toward the floor in a frog-like position, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Start on all fours in a tabletop position.',
      'Slowly slide your knees out to the sides as wide as is comfortable.',
      'Turn your feet outward so your inner ankles, shins, and knees are in contact with the floor.',
      'Keep your ankles in line with your knees (do not let your feet drift inward).',
      'Lower your forearms to the floor for support and to deepen the stretch.',
      'Let your hips sink toward the floor, feeling the stretch in the inner thighs and groin.',
      'Hold and breathe slowly.',
    ],
    tips: [
      'Move into this stretch slowly — the adductors respond better to gradual, sustained pressure.',
      'Do not push past sharp pain in the groin or inner knee.',
      'Place a folded blanket under your knees for padding.',
      'Keep your spine long — avoid letting your lower back arch excessively.',
    ],
    modifications: {
      easier: 'Perform Butterfly Stretch seated instead for a gentler inner thigh and groin opener.',
      harder: 'Press your hips further back toward your heels while keeping knees wide to intensify the stretch.',
    },
    benefits: [
      'Deeply stretches the adductors and inner thighs',
      'Opens the hip flexors',
      'Improves hip abduction and external rotation',
      'Helpful for athletes in sports requiring wide stances',
      'Reduces stiffness from prolonged sitting',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'lizard-pose',
    name: 'Lizard Pose',
    difficulty: 'intermediate',
    targetMuscles: ['hip flexors', 'groin', 'hamstrings', 'inner thigh', 'psoas'],
    bodyAreas: ['hips', 'hamstrings'],
    illustrationFile: 'lizard-pose.svg',
    illustrationPrompt:
      'Flat vector illustration of a person in a deep lunge with the front foot placed outside the hand on the same side, both forearms lowered to the floor inside the front foot, back leg extended straight behind, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Start in a high plank position.',
      'Step your right foot forward and place it to the outside of your right hand.',
      'Lower your back (left) knee to the mat.',
      'Walk your right foot slightly further forward if needed to give your hips space to sink.',
      'Lower your forearms to the floor inside your right foot.',
      'Keep your hips square toward the floor and your back leg extended.',
      'Let your hips melt toward the floor, feeling the stretch through the hip flexor and groin.',
      'Hold, then switch sides.',
    ],
    tips: [
      'Keep your front knee tracking over your front foot — do not let it collapse inward.',
      'If forearms do not reach the floor, use yoga blocks under your hands.',
      'Press the ball of your back foot into the floor for stability.',
      'Breathe into the front of the hip of your back leg.',
    ],
    modifications: {
      easier: 'Keep hands on the floor (not forearms) to reduce the depth of the stretch.',
      harder: 'Lift the back knee off the floor so both legs are straight and extended for full Lizard Pose.',
    },
    benefits: [
      'Deeply stretches the hip flexors and psoas',
      'Opens the groin and inner thigh of the front leg',
      'Improves hip extension and flexion range of motion',
      'Strengthens the hip stabilizers',
      'Counteracts tightness from prolonged sitting or running',
    ],
    defaultHoldSeconds: 45,
  },
  {
    id: '90-90-stretch',
    name: '90/90 Stretch',
    difficulty: 'intermediate',
    targetMuscles: ['hip internal rotators', 'hip external rotators', 'piriformis', 'glutes', 'hip flexors'],
    bodyAreas: ['hips'],
    illustrationFile: '90-90-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person sitting on the floor with both legs bent at 90-degree angles, one shin in front and one shin to the side, torso upright and hands resting on the floor behind for support, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Sit on the floor with your right leg in front of you, bent at 90 degrees, shin parallel to the front of your mat.',
      'Position your left leg behind you, also bent at 90 degrees, with your shin pointing out to the left.',
      'Both knees should be bent to approximately 90 degrees.',
      'Place your hands on the floor behind you for support.',
      'Sit tall and square your hips toward your front shin.',
      'Hold the position, feeling the stretch in the outer right hip and the inner left hip.',
      'To deepen, hinge forward from the hips over the front shin.',
      'Switch sides by rotating the legs to the opposite configuration.',
    ],
    tips: [
      'Keep both sit bones as even to the floor as possible — use a block under the elevated hip if needed.',
      'Your front foot should be flexed to protect the knee.',
      'Do not force your torso to fold forward — stay upright and focus on the hip position first.',
      'This stretch targets both internal and external rotation simultaneously, so go slowly.',
    ],
    modifications: {
      easier: 'Sit on a folded blanket to elevate the hips, making it easier to achieve the 90/90 position.',
      harder: 'Fold forward over your front leg, walking your hands out in front of you while maintaining the 90/90 position.',
    },
    benefits: [
      'Improves hip internal and external rotation simultaneously',
      'Stretches the piriformis and deep hip rotators',
      'Addresses hip asymmetries common in athletes',
      'Prepares the hips for deep squatting movements',
      'Reduces lower back tension caused by hip stiffness',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'hip-circles',
    name: 'Hip Circles',
    difficulty: 'beginner',
    targetMuscles: ['hip flexors', 'hip external rotators', 'glutes', 'lower back', 'adductors'],
    bodyAreas: ['hips', 'lower-back'],
    illustrationFile: 'hip-circles.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing with feet shoulder-width apart and hands on their hips, performing a circular motion with their hips as indicated by a subtle curved arrow, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet shoulder-width apart and place your hands on your hips.',
      'Keep your upper body relatively still and begin rotating your hips in a large, slow circle.',
      'Move your hips forward, then to the right, then back, then to the left.',
      'Make the circles as large and controlled as possible.',
      'Complete 5–10 slow circles in one direction.',
      'Pause and reverse the direction for another 5–10 circles.',
      'Breathe naturally throughout the movement.',
    ],
    tips: [
      'Keep your knees slightly soft — avoid locking them out.',
      'Let the movement originate from the hips, not the lower back.',
      'Go slowly to feel each range of the circle — do not rush.',
      'Keep your core lightly engaged to support the lumbar spine.',
    ],
    modifications: {
      easier: 'Perform smaller, shallower circles and hold onto a wall or chair for balance.',
      harder: 'Increase the size of the circles, slow down the tempo, or hold for 2–3 seconds at the end range positions (front, side, back).',
    },
    benefits: [
      'Lubricates the hip joint by circulating synovial fluid',
      'Warms up the hip flexors, extensors, and rotators',
      'Improves functional hip mobility for daily movement',
      'Reduces stiffness after sitting or sleeping',
      'Gentle enough to use as a warm-up or cool-down',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'reclined-hip-opener',
    name: 'Reclined Hip Opener',
    difficulty: 'beginner',
    targetMuscles: ['hip external rotators', 'inner thigh', 'groin', 'glutes'],
    bodyAreas: ['hips'],
    illustrationFile: 'reclined-hip-opener.svg',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their back with one knee drawn toward the chest and gently guided across the body to the opposite side in a supine twist while the opposite arm is stretched out to the side, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your back with your legs extended.',
      'Draw your right knee toward your chest.',
      'Place your left hand on the outside of your right knee.',
      'Gently guide your right knee across your body toward the floor on your left side.',
      'Extend your right arm out to the right side at shoulder height, palm facing up.',
      'Keep both shoulders in contact with the floor.',
      'Relax and let gravity deepen the stretch in your outer hip and lower back.',
      'Hold, then return to center and switch sides.',
    ],
    tips: [
      'Do not force the knee to the floor — let it rest wherever gravity takes it.',
      'Focus on keeping the opposite shoulder grounded rather than getting the knee lower.',
      'This is also a gentle spinal rotation — breathe into both the hip and the upper back.',
      'Keep your neck relaxed and gaze up toward the ceiling.',
    ],
    modifications: {
      easier: 'Place a folded blanket or block under the lowered knee so it does not have to travel as far.',
      harder: 'Actively press the opposite shoulder into the floor while drawing the knee further across the body, and hold for 60 seconds.',
    },
    benefits: [
      'Stretches the outer hip and external hip rotators',
      'Gently rotates and decompresses the spine',
      'Releases tension in the glutes and IT band',
      'Accessible for those with limited mobility',
      'Calming stretch suitable for end-of-day recovery',
    ],
    defaultHoldSeconds: 30,
  },
];
