import { Exercise } from '../types';

export const legExercises: Exercise[] = [
  {
    id: 'standing-quad-stretch',
    name: 'Standing Quad Stretch',
    difficulty: 'beginner',
    targetMuscles: ['quadriceps', 'rectus femoris', 'hip flexors'],
    bodyAreas: ['quadriceps', 'hips'],
    illustrationFile: 'standing-quad-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing on one leg with the other foot pulled up behind them toward their glutes, hand gripping the ankle with their knee pointing straight down, free arm slightly out for balance, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand tall with your feet hip-width apart near a wall or chair for balance if needed.',
      'Shift your weight onto your left foot.',
      'Bend your right knee and lift your right foot behind you toward your glutes.',
      'Grasp your right ankle with your right hand.',
      'Draw your knee directly downward — keep both knees close together.',
      'Stand tall, keeping your hips square and your core lightly engaged.',
      'Hold until you feel a stretch along the front of your right thigh.',
      'Switch sides.',
    ],
    tips: [
      'Avoid pulling your foot outward to the side — the knee should point straight down.',
      'Keep your pelvis neutral — do not arch your lower back to achieve the stretch.',
      'Use a wall or the back of a chair with your free hand if balance is challenging.',
      'Squeeze your standing-leg glute for extra balance and stability.',
    ],
    modifications: {
      easier: 'Stand next to a wall and place your free hand on it for support.',
      harder: 'Reach the same-side arm overhead and lean gently forward to incorporate a hip flexor stretch.',
    },
    benefits: [
      'Stretches all four quadriceps muscles',
      'Releases the rectus femoris and hip flexors',
      'Improves knee flexion range of motion',
      'Reduces post-exercise soreness in the thighs',
      'Improves balance and single-leg stability',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'lying-quad-stretch',
    name: 'Lying Quad Stretch',
    difficulty: 'beginner',
    targetMuscles: ['quadriceps', 'rectus femoris', 'hip flexors'],
    bodyAreas: ['quadriceps', 'hips'],
    illustrationFile: 'lying-quad-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person lying on their side on the floor with the top knee bent and the top hand pulling the top foot toward their glutes, body in a straight line, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Lie on your right side on a mat, with your body in a straight line.',
      'Rest your head on your right arm or on a folded blanket.',
      'Bend your top (left) knee and bring your left heel toward your left glute.',
      'Reach back with your left hand and grasp your left ankle or the top of your left foot.',
      'Gently draw your foot closer to your glute while pushing your hip slightly forward.',
      'Keep your knees together and your body in one long line.',
      'Hold until you feel a stretch in the front of the left thigh.',
      'Switch sides.',
    ],
    tips: [
      'Keep both knees stacked on top of each other throughout the stretch.',
      'Do not let your lower back collapse — maintain a neutral spine.',
      'If you cannot reach your ankle, use a strap or towel looped around your foot.',
      'This variation is ideal for those who struggle with balance in the standing version.',
    ],
    modifications: {
      easier: 'Loop a resistance band or yoga strap around your ankle if you cannot reach your foot.',
      harder: 'Tuck your pelvis under slightly to engage a deeper hip flexor and rectus femoris stretch.',
    },
    benefits: [
      'Stretches the quadriceps without requiring balance',
      'Targets the rectus femoris from a hip-neutral position',
      'Helpful for people with knee pain who cannot stand on one leg',
      'Reduces anterior knee tension',
      'Good for post-run or post-cycling recovery',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'standing-hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    difficulty: 'beginner',
    targetMuscles: ['hamstrings', 'biceps femoris', 'semitendinosus', 'semimembranosus', 'calves'],
    bodyAreas: ['hamstrings', 'calves'],
    illustrationFile: 'standing-hamstring-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing and placing one heel on a low surface in front of them with the leg straight, leaning slightly forward from the hips with a flat back and hands resting on the thigh, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand in front of a low step, bench, or sturdy chair.',
      'Place your right heel on the surface with your leg straight.',
      'Stand tall on your left leg with a soft bend in the knee.',
      'Hinge forward from your hips — keep your back flat, do not round your spine.',
      'Rest your hands on your right thigh for support.',
      'Hold until you feel a pull along the back of your right thigh.',
      'To release, bend your right knee slightly and step the foot down.',
      'Switch sides.',
    ],
    tips: [
      'Lead with your chest when hinging forward — a flat back produces a better stretch than rounding.',
      'Keep your raised foot flexed (toes pointing up) to deepen the stretch through the calf.',
      'Do not lock the standing knee — keep a slight, soft bend to protect the joint.',
      'The height of the surface controls intensity — lower surfaces are easier.',
    ],
    modifications: {
      easier: 'Rest your heel on the floor in front of you (no surface needed) for a gentler option.',
      harder: 'Raise the heel to a higher surface such as a bench or stair rail and deepen the forward hinge.',
    },
    benefits: [
      'Stretches the entire hamstring group (biceps femoris, semitendinosus, semimembranosus)',
      'Improves hip flexion range of motion',
      'Reduces lower back tension caused by tight hamstrings',
      'Helpful for runners, cyclists, and desk workers',
      'Promotes better posterior chain flexibility',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'seated-forward-fold',
    name: 'Seated Forward Fold',
    difficulty: 'beginner',
    targetMuscles: ['hamstrings', 'lower back', 'calves', 'spine extensors'],
    bodyAreas: ['hamstrings', 'lower-back', 'calves'],
    illustrationFile: 'seated-forward-fold.svg',
    illustrationPrompt:
      'Flat vector illustration of a person sitting on the floor with both legs extended straight in front of them and their torso folded forward over the legs, hands reaching toward their feet, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Sit on the floor with your legs extended straight in front of you.',
      'Flex your feet so your toes point toward the ceiling.',
      'Sit tall, lengthening your spine from the base to the crown of the head.',
      'Inhale and reach your arms overhead.',
      'Exhale and hinge forward from your hips, reaching your hands toward your feet or shins.',
      'Keep your back as flat as possible — avoid rounding aggressively at the lower back.',
      'Hold the stretch, letting gravity deepen the fold with each exhale.',
      'To release, press your hands into the floor and slowly sit back up.',
    ],
    tips: [
      'Sit on a folded blanket if your hips tip backward — this makes it much easier to hinge forward.',
      'Bend your knees slightly if your hamstrings are very tight to allow a flatter back.',
      'Use a strap around the balls of your feet to reach forward without rounding.',
      'Aim for length in your spine, not maximum distance of your hands — quality over range.',
    ],
    modifications: {
      easier: 'Bend both knees generously and hold them, rather than reaching for the feet.',
      harder: 'Work toward pressing the back of your knees flat against the floor while maintaining maximum forward reach.',
    },
    benefits: [
      'Provides a comprehensive stretch for the entire hamstring group',
      'Lengthens the lumbar spine and erector spinae',
      'Stretches the calves and plantar fascia',
      'Calms the nervous system in a forward fold position',
      'Counteracts tightness from prolonged sitting',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'toe-touch',
    name: 'Toe Touch',
    difficulty: 'beginner',
    targetMuscles: ['hamstrings', 'lower back', 'calves', 'glutes'],
    bodyAreas: ['hamstrings', 'lower-back', 'calves'],
    illustrationFile: 'toe-touch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing with feet together bending forward at the waist with arms hanging down toward their toes, head relaxed between the arms, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet together or hip-width apart.',
      'Take a deep breath in and stand tall.',
      'Exhale and slowly hinge forward from your hips, sweeping your arms down toward the floor.',
      'Let your head and neck relax completely, hanging heavy.',
      'Reach for your toes, shins, or as far as you can comfortably go.',
      'Bend your knees slightly if your hamstrings are very tight.',
      'Hold the position, breathing deeply.',
      'To return, slowly roll up one vertebra at a time, or hinge back up with a flat back.',
    ],
    tips: [
      'Do not bounce — a slow, sustained hold is safer and more effective.',
      'Keep a soft bend in your knees to avoid excessive strain on the lower back.',
      'Let gravity do the work — relax the muscles in your back and hamstrings rather than forcing down.',
      'Roll up slowly to avoid a head rush when returning to standing.',
    ],
    modifications: {
      easier: 'Bend your knees generously to bring your torso closer to your thighs and reduce hamstring tension.',
      harder: 'Cross your feet (right over left) to add a calf stretch element, hold for 20 seconds, then switch.',
    },
    benefits: [
      'Stretches the entire posterior chain from calves to lower back',
      'Decompresses the lumbar spine with gravity assistance',
      'Quick and accessible — can be done anywhere, any time',
      'Improves overall spinal and posterior flexibility',
      'Serves as a good warm-up assessment for hamstring tightness',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'standing-calf-stretch',
    name: 'Standing Calf Stretch',
    difficulty: 'beginner',
    targetMuscles: ['gastrocnemius', 'calves', 'Achilles tendon'],
    bodyAreas: ['calves'],
    illustrationFile: 'standing-calf-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing facing a wall with both hands flat on the wall, one foot stepped back with the heel pressed firmly into the floor and the leg straight, the other foot closer to the wall with a bent knee, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand facing a wall and place both palms flat against it at shoulder height.',
      'Step your right foot back about 60–90 cm, keeping your heel on the floor.',
      'Keep your right leg straight and your right foot pointed forward.',
      'Bend your left knee slightly, shifting your weight forward.',
      'Press your right heel firmly into the floor.',
      'Lean your hips slightly toward the wall until you feel a stretch in the back of your right lower leg.',
      'Hold the stretch.',
      'Switch sides.',
    ],
    tips: [
      'Keep the back foot pointed straight forward — do not let it turn outward.',
      'Press through the entire heel, not just the outside edge of the foot.',
      'The further back you step, the greater the stretch intensity.',
      'Keep your hips square and facing the wall throughout.',
    ],
    modifications: {
      easier: 'Step back less distance from the wall for a gentler stretch.',
      harder: 'Stand on a step with your heel hanging off the edge and lower it toward the floor for a deeper loaded stretch.',
    },
    benefits: [
      'Stretches the gastrocnemius (upper calf) muscle',
      'Lengthens the Achilles tendon',
      'Reduces calf tightness after running or walking',
      'Helps prevent plantar fasciitis and Achilles tendinopathy',
      'Improves ankle dorsiflexion range of motion',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'wall-calf-stretch',
    name: 'Wall Calf Stretch',
    difficulty: 'beginner',
    targetMuscles: ['gastrocnemius', 'calves', 'Achilles tendon', 'plantar fascia'],
    bodyAreas: ['calves'],
    illustrationFile: 'wall-calf-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing facing a wall placing the ball of one foot against the base of the wall with toes up and the heel on the floor, leaning forward gently with hands on the wall, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand facing a wall and place the ball of your right foot against the base of the wall.',
      'Keep your right heel on the floor and your toes pressing against the wall at roughly 45 degrees.',
      'Straighten your right leg.',
      'Place both hands on the wall for support.',
      'Lean your body forward gently — do not lock out the knee.',
      'Feel the stretch along the back of the lower leg and into the Achilles tendon.',
      'Hold, then switch sides.',
    ],
    tips: [
      'The angle of your foot against the wall determines intensity — a steeper angle means a deeper stretch.',
      'Keep your heel pressed flat on the floor throughout.',
      'This position also gently stretches the plantar fascia — useful for those with foot pain.',
      'Do not hyperextend the knee — maintain a micro-bend if needed.',
    ],
    modifications: {
      easier: 'Place the foot at a shallower angle against the wall (less than 45 degrees).',
      harder: 'Increase the foot angle and lean into the wall more, or perform with a bent knee to target the soleus.',
    },
    benefits: [
      'Targets the gastrocnemius with the ankle in dorsiflexion',
      'Stretches the plantar fascia simultaneously',
      'Effective for relieving morning heel pain',
      'Improves ankle mobility for squatting and walking',
      'Simple and effective post-run recovery tool',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'soleus-stretch',
    name: 'Soleus Stretch',
    difficulty: 'beginner',
    targetMuscles: ['soleus', 'lower calf', 'Achilles tendon'],
    bodyAreas: ['calves'],
    illustrationFile: 'soleus-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing facing a wall with both hands on the wall and one foot stepped back with the knee bent and the heel pressed into the floor, leaning forward to feel the stretch in the lower calf, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand facing a wall with both palms on the wall.',
      'Step your right foot back about 30–45 cm.',
      'Bend your right knee while keeping your right heel pressed firmly on the floor.',
      'Lean your body toward the wall until you feel a deeper stretch in the lower calf, just above the heel.',
      'Keep your right foot pointed forward.',
      'Hold the stretch.',
      'Switch sides.',
    ],
    tips: [
      'The bent-knee position is what distinguishes this from a regular calf stretch — it isolates the soleus.',
      'Keep your heel on the floor — the moment it lifts, you lose the stretch.',
      'The soleus responds to sustained, moderate pressure rather than aggressive stretching.',
      'This stretch is especially important for runners and cyclists who develop tight lower calves.',
    ],
    modifications: {
      easier: 'Reduce the distance you step back and the amount you lean forward.',
      harder: 'Perform the stretch on a slightly downward slope (like a driveway) with your heel lower than your toes.',
    },
    benefits: [
      'Specifically targets the soleus, which lies beneath the gastrocnemius',
      'Reduces lower Achilles tension — a common injury site',
      'Improves ankle dorsiflexion needed for deep squats and lunges',
      'Helpful for runners and those recovering from Achilles tendinopathy',
      'Complements gastrocnemius stretching for complete calf flexibility',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'it-band-stretch',
    name: 'IT Band Stretch',
    difficulty: 'intermediate',
    targetMuscles: ['iliotibial band', 'tensor fasciae latae', 'outer hip', 'glutes'],
    bodyAreas: ['quadriceps', 'hips'],
    illustrationFile: 'it-band-stretch.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing with one foot crossed behind the other, leaning sideways away from the back foot with one arm reaching overhead and to the side to create a long lateral stretch along the outer leg and hip, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand near a wall for optional balance support.',
      'Cross your right foot behind your left foot.',
      'Press your right hip out to the right side.',
      'Extend your right arm up and over toward the left, creating a long arc through the right side of your body.',
      'You can place your left hand on your hip or on the wall for support.',
      'Feel the stretch running from your outer right hip down the length of your right outer thigh.',
      'Hold, then switch sides.',
    ],
    tips: [
      'The key is pressing the hip outward — the lateral lean alone is not enough.',
      'Keep both feet flat on the floor, especially the heel of the back foot.',
      'Do not rotate your torso — keep your chest facing forward.',
      'This stretch requires patience — the IT band responds slowly to sustained holds.',
    ],
    modifications: {
      easier: 'Do a smaller lateral lean and limit how far you cross your feet.',
      harder: 'Perform the stretch with the back foot placed on a low step or curb to elevate and increase the lateral tension.',
    },
    benefits: [
      'Stretches the iliotibial band along the outer thigh',
      'Releases the tensor fasciae latae (TFL) in the outer hip',
      'Helps prevent IT band syndrome common in runners and cyclists',
      'Reduces lateral knee pain',
      'Improves lateral hip and thigh flexibility',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'inner-thigh-squat',
    name: 'Inner Thigh Squat',
    difficulty: 'beginner',
    targetMuscles: ['adductors', 'inner thighs', 'groin', 'hip flexors', 'calves'],
    bodyAreas: ['hips', 'quadriceps', 'calves'],
    illustrationFile: 'inner-thigh-squat.svg',
    illustrationPrompt:
      'Flat vector illustration of a person in a wide-stance squat with feet turned out at 45 degrees and knees pressing outward, hands pressed together at the chest or resting on inner thighs, hips low and spine upright, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet wider than shoulder-width apart, toes turned out at 45 degrees.',
      'Place your hands on your inner thighs or press your palms together at your chest.',
      'Slowly lower your hips toward the floor, bending your knees in the direction of your toes.',
      'Descend until your thighs are parallel to the floor or your inner thighs feel a stretch.',
      'Press your elbows or hands gently against the inside of your knees to open the groin.',
      'Keep your chest lifted and your spine long.',
      'Hold the position, breathing steadily.',
      'Press through your heels to return to standing.',
    ],
    tips: [
      'Keep your heels on the floor — if they lift, widen your stance slightly or elevate them on a small wedge.',
      'Track your knees directly over your toes — do not let them cave inward.',
      'Use your elbows on your inner thighs to gently deepen the groin stretch.',
      'If holding the squat is tiring, hold a doorframe or suspension trainer for support.',
    ],
    modifications: {
      easier: 'Hold a doorframe or TRX strap with both hands and sit back into a supported squat.',
      harder: 'Slowly shift your weight to one side into a lateral squat to deepen the adductor stretch on the opposite leg.',
    },
    benefits: [
      'Stretches the adductors and inner thighs',
      'Opens the groin and hip flexors',
      'Improves ankle and hip mobility simultaneously',
      'Develops functional squat depth',
      'Useful for activities requiring low, wide stances such as yoga, martial arts, and weightlifting',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'wide-leg-forward-bend',
    name: 'Wide Leg Forward Bend',
    difficulty: 'intermediate',
    targetMuscles: ['adductors', 'hamstrings', 'inner thighs', 'lower back', 'calves'],
    bodyAreas: ['hamstrings', 'hips', 'lower-back'],
    illustrationFile: 'wide-leg-forward-bend.svg',
    illustrationPrompt:
      'Flat vector illustration of a person standing with their legs spread wide apart in a straddle position and folding their torso straight down toward the floor, hands touching the floor between their feet or reaching forward, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Stand with your feet spread wide — roughly 3 to 4 feet apart.',
      'Turn your toes slightly inward (pigeon-toed) or keep them facing forward.',
      'Place your hands on your hips.',
      'Inhale to lengthen your spine.',
      'Exhale and hinge forward from your hips, lowering your torso toward the floor.',
      'Place your hands on the floor, on blocks, or interlace them behind your back.',
      'Let the crown of your head reach toward the floor.',
      'Hold, feeling the stretch in your inner thighs and hamstrings.',
      'To return, press through your feet and hinge back up with a flat back.',
    ],
    tips: [
      'Keep the outer edges of your feet pressing firmly into the floor.',
      'If your hands do not reach the floor, use yoga blocks.',
      'Do not lock your knees — maintain a micro-bend to protect the joints.',
      'To intensify, walk your hands further forward between your feet.',
    ],
    modifications: {
      easier: 'Place blocks under your hands to reduce how far down you need to fold.',
      harder: 'Walk your hands further forward along the floor, bringing your torso parallel to the ground or deeper.',
    },
    benefits: [
      'Deeply stretches the adductors and inner thighs',
      'Lengthens the hamstrings of both legs simultaneously',
      'Decompresses the lumbar spine in the inverted position',
      'Improves hip abduction and flexibility for lateral movements',
      'Helps prepare for deeper poses like splits',
    ],
    defaultHoldSeconds: 30,
  },
  {
    id: 'ankle-circles',
    name: 'Ankle Circles',
    difficulty: 'beginner',
    targetMuscles: ['ankles', 'calves', 'tibialis anterior', 'peroneals', 'foot intrinsics'],
    bodyAreas: ['calves'],
    illustrationFile: 'ankle-circles.svg',
    illustrationPrompt:
      'Flat vector illustration of a person sitting on the floor or a chair with one leg extended and the foot lifted off the ground, rotating the ankle in a slow circular motion indicated by a subtle curved arrow around the foot, warm earthy color palette with cream background, sage green and terracotta accents, minimal clean lines, no text, no shadows, wellness mobile app style, 400x400px',
    instructions: [
      'Sit on a chair or on the floor with your legs in front of you.',
      'Lift your right foot slightly off the floor.',
      'Keeping your leg still, begin rotating your right foot in a large, slow circle at the ankle.',
      'Rotate clockwise for 10 full circles, making each circle as large as possible.',
      'Pause, then reverse and rotate counter-clockwise for 10 circles.',
      'Switch feet and repeat on the left ankle.',
      'Breathe naturally throughout the movement.',
    ],
    tips: [
      'Keep your lower leg still — the movement should come entirely from the ankle, not the knee.',
      'Make each circle as large and slow as possible to cover the full range of motion.',
      'Point your toes as far as you can at the bottom of each circle and flex them at the top.',
      'This is an excellent morning routine or pre-walk warm-up for the ankles and feet.',
    ],
    modifications: {
      easier: 'Sit in a chair rather than on the floor for easier access to the foot.',
      harder: 'Perform ankle circles while standing on one leg to add a balance and stability challenge.',
    },
    benefits: [
      'Lubricates the ankle joint and promotes synovial fluid circulation',
      'Warms up the tibialis anterior, peroneals, and calf complex',
      'Improves ankle mobility and proprioception',
      'Reduces stiffness and swelling after periods of inactivity',
      'Helps prevent ankle sprains by improving joint awareness',
    ],
    defaultHoldSeconds: 20,
  },
];
