/* Auto-generated — do not edit manually */
import type { ImageSourcePropType } from "react-native";

const illustrations: Record<string, ImageSourcePropType> = {
  "90_90_hip_switch.png": require("@/assets/illustrations/90_90_hip_switch.png"),
  "90_90_hip_switch_extension.png": require("@/assets/illustrations/90_90_hip_switch_extension.png"),
  "90_90_hip_switch_no_hands.png": require("@/assets/illustrations/90_90_hip_switch_no_hands.png"),
  "air_squats.png": require("@/assets/illustrations/air_squats.png"),
  "airplane.png": require("@/assets/illustrations/airplane.png"),
  "ankle_circles.png": require("@/assets/illustrations/ankle_circles.png"),
  "aquaman.png": require("@/assets/illustrations/aquaman.png"),
  "arm_circles.png": require("@/assets/illustrations/arm_circles.png"),
  "arm_swings.png": require("@/assets/illustrations/arm_swings.png"),
  "bent_arm_pike.png": require("@/assets/illustrations/bent_arm_pike.png"),
  "bent_over_calf.png": require("@/assets/illustrations/bent_over_calf.png"),
  "bicycle_crunch_hold.png": require("@/assets/illustrations/bicycle_crunch_hold.png"),
  "bird_dog.png": require("@/assets/illustrations/bird_dog.png"),
  "bird_dog_plank.png": require("@/assets/illustrations/bird_dog_plank.png"),
  "bridge.png": require("@/assets/illustrations/bridge.png"),
  "bridge_leg_lift.png": require("@/assets/illustrations/bridge_leg_lift.png"),
  "bulldog.png": require("@/assets/illustrations/bulldog.png"),
  "butt_kicks.png": require("@/assets/illustrations/butt_kicks.png"),
  "butterfly.png": require("@/assets/illustrations/butterfly.png"),
  "cactus_arms.png": require("@/assets/illustrations/cactus_arms.png"),
  "cat_cow.png": require("@/assets/illustrations/cat_cow.png"),
  "chest_opener.png": require("@/assets/illustrations/chest_opener.png"),
  "childs_pose.png": require("@/assets/illustrations/childs_pose.png"),
  "chin_retractions.png": require("@/assets/illustrations/chin_retractions.png"),
  "cross_leg_fold.png": require("@/assets/illustrations/cross_leg_fold.png"),
  "crunch_hold.png": require("@/assets/illustrations/crunch_hold.png"),
  "curtsy_lunge_hold.png": require("@/assets/illustrations/curtsy_lunge_hold.png"),
  "dead_bug.png": require("@/assets/illustrations/dead_bug.png"),
  "deep_split_squat.png": require("@/assets/illustrations/deep_split_squat.png"),
  "dip_hold.png": require("@/assets/illustrations/dip_hold.png"),
  "diver.png": require("@/assets/illustrations/diver.png"),
  "doorway_pecs.png": require("@/assets/illustrations/doorway_pecs.png"),
  "double_pigeon.png": require("@/assets/illustrations/double_pigeon.png"),
  "downward_dog.png": require("@/assets/illustrations/downward_dog.png"),
  "dynamic_quad_stretch.png": require("@/assets/illustrations/dynamic_quad_stretch.png"),
  "dynamic_side_bends.png": require("@/assets/illustrations/dynamic_side_bends.png"),
  "dynamic_wide_leg_forward_fold.png": require("@/assets/illustrations/dynamic_wide_leg_forward_fold.png"),
  "ear_to_shoulder.png": require("@/assets/illustrations/ear_to_shoulder.png"),
  "elbow_pike.png": require("@/assets/illustrations/elbow_pike.png"),
  "elbow_plank.png": require("@/assets/illustrations/elbow_plank.png"),
  "elbow_plank_leg_lift.png": require("@/assets/illustrations/elbow_plank_leg_lift.png"),
  "elbow_side_plank.png": require("@/assets/illustrations/elbow_side_plank.png"),
  "elbow_side_plank_leg_lift.png": require("@/assets/illustrations/elbow_side_plank_leg_lift.png"),
  "folded_butterfly.png": require("@/assets/illustrations/folded_butterfly.png"),
  "forearm_stretch.png": require("@/assets/illustrations/forearm_stretch.png"),
  "forward_fold.png": require("@/assets/illustrations/forward_fold.png"),
  "frog_pose.png": require("@/assets/illustrations/frog_pose.png"),
  "front_split.png": require("@/assets/illustrations/front_split.png"),
  "gate_opener.png": require("@/assets/illustrations/gate_opener.png"),
  "good_mornings.png": require("@/assets/illustrations/good_mornings.png"),
  "hamstring_pulls.png": require("@/assets/illustrations/hamstring_pulls.png"),
  "hamstring_scoops.png": require("@/assets/illustrations/hamstring_scoops.png"),
  "hand_plank.png": require("@/assets/illustrations/hand_plank.png"),
  "hand_plank_leg_lift.png": require("@/assets/illustrations/hand_plank_leg_lift.png"),
  "hand_side_plank.png": require("@/assets/illustrations/hand_side_plank.png"),
  "hand_side_plank_leg_lift.png": require("@/assets/illustrations/hand_side_plank_leg_lift.png"),
  "happy_baby.png": require("@/assets/illustrations/happy_baby.png"),
  "heel_to_toe_rocks.png": require("@/assets/illustrations/heel_to_toe_rocks.png"),
  "high_knee_twists.png": require("@/assets/illustrations/high_knee_twists.png"),
  "high_knees.png": require("@/assets/illustrations/high_knees.png"),
  "hip_circles.png": require("@/assets/illustrations/hip_circles.png"),
  "hollow_body.png": require("@/assets/illustrations/hollow_body.png"),
  "hurdler.png": require("@/assets/illustrations/hurdler.png"),
  "jumping_jacks.png": require("@/assets/illustrations/jumping_jacks.png"),
  "knee_circles.png": require("@/assets/illustrations/knee_circles.png"),
  "kneeling_hip_circles.png": require("@/assets/illustrations/kneeling_hip_circles.png"),
  "kneeling_psoas.png": require("@/assets/illustrations/kneeling_psoas.png"),
  "kneeling_quad.png": require("@/assets/illustrations/kneeling_quad.png"),
  "knees_hugs.png": require("@/assets/illustrations/knees_hugs.png"),
  "knees_to_chest.png": require("@/assets/illustrations/knees_to_chest.png"),
  "lateral_foot_rocks.png": require("@/assets/illustrations/lateral_foot_rocks.png"),
  "lateral_leg_swing.png": require("@/assets/illustrations/lateral_leg_swing.png"),
  "lateral_lunge.png": require("@/assets/illustrations/lateral_lunge.png"),
  "leaning_calf.png": require("@/assets/illustrations/leaning_calf.png"),
  "leg_lift.png": require("@/assets/illustrations/leg_lift.png"),
  "leg_swings.png": require("@/assets/illustrations/leg_swings.png"),
  "legs_up_wall.png": require("@/assets/illustrations/legs_up_wall.png"),
  "lizard_pose.png": require("@/assets/illustrations/lizard_pose.png"),
  "locust_pose.png": require("@/assets/illustrations/locust_pose.png"),
  "lunge.png": require("@/assets/illustrations/lunge.png"),
  "lying_figure_four.png": require("@/assets/illustrations/lying_figure_four.png"),
  "lying_hamstring.png": require("@/assets/illustrations/lying_hamstring.png"),
  "lying_quad_stretch.png": require("@/assets/illustrations/lying_quad_stretch.png"),
  "lying_side_leg_raise.png": require("@/assets/illustrations/lying_side_leg_raise.png"),
  "modified_seated_twist.png": require("@/assets/illustrations/modified_seated_twist.png"),
  "narrow_push_up_hold.png": require("@/assets/illustrations/narrow_push_up_hold.png"),
  "narrow_squat_hold.png": require("@/assets/illustrations/narrow_squat_hold.png"),
  "neck_extension.png": require("@/assets/illustrations/neck_extension.png"),
  "neck_flex.png": require("@/assets/illustrations/neck_flex.png"),
  "neck_flexion.png": require("@/assets/illustrations/neck_flexion.png"),
  "neck_laterals.png": require("@/assets/illustrations/neck_laterals.png"),
  "neck_roll.png": require("@/assets/illustrations/neck_roll.png"),
  "neck_rotation.png": require("@/assets/illustrations/neck_rotation.png"),
  "one_arm_hug.png": require("@/assets/illustrations/one_arm_hug.png"),
  "overhead_reach.png": require("@/assets/illustrations/overhead_reach.png"),
  "overhead_tricep.png": require("@/assets/illustrations/overhead_tricep.png"),
  "pelvic_tilt_press.png": require("@/assets/illustrations/pelvic_tilt_press.png"),
  "pigeon.png": require("@/assets/illustrations/pigeon.png"),
  "pike.png": require("@/assets/illustrations/pike.png"),
  "pistol_squat_hold.png": require("@/assets/illustrations/pistol_squat_hold.png"),
  "plow.png": require("@/assets/illustrations/plow.png"),
  "puppy_pose.png": require("@/assets/illustrations/puppy_pose.png"),
  "push_up_hold.png": require("@/assets/illustrations/push_up_hold.png"),
  "quad_stretch.png": require("@/assets/illustrations/quad_stretch.png"),
  "rag_doll.png": require("@/assets/illustrations/rag_doll.png"),
  "reclined_butterfly.png": require("@/assets/illustrations/reclined_butterfly.png"),
  "reverse_lunge.png": require("@/assets/illustrations/reverse_lunge.png"),
  "reverse_plank.png": require("@/assets/illustrations/reverse_plank.png"),
  "reverse_plank_leg_lift.png": require("@/assets/illustrations/reverse_plank_leg_lift.png"),
  "reverse_shoulder.png": require("@/assets/illustrations/reverse_shoulder.png"),
  "runners_lunge_twist.png": require("@/assets/illustrations/runners_lunge_twist.png"),
  "scalene_stretch.png": require("@/assets/illustrations/scalene_stretch.png"),
  "scapula_stretch.png": require("@/assets/illustrations/scapula_stretch.png"),
  "seated_figure_four.png": require("@/assets/illustrations/seated_figure_four.png"),
  "seated_fold.png": require("@/assets/illustrations/seated_fold.png"),
  "seated_hamstring.png": require("@/assets/illustrations/seated_hamstring.png"),
  "seated_straddle.png": require("@/assets/illustrations/seated_straddle.png"),
  "seated_twist.png": require("@/assets/illustrations/seated_twist.png"),
  "shoulder_cross.png": require("@/assets/illustrations/shoulder_cross.png"),
  "shoulder_opener.png": require("@/assets/illustrations/shoulder_opener.png"),
  "shoulder_rolls.png": require("@/assets/illustrations/shoulder_rolls.png"),
  "shoulder_stand.png": require("@/assets/illustrations/shoulder_stand.png"),
  "side_bend.png": require("@/assets/illustrations/side_bend.png"),
  "side_lunge.png": require("@/assets/illustrations/side_lunge.png"),
  "side_lunge_hold.png": require("@/assets/illustrations/side_lunge_hold.png"),
  "single_arm_plank.png": require("@/assets/illustrations/single_arm_plank.png"),
  "single_knee_to_chest.png": require("@/assets/illustrations/single_knee_to_chest.png"),
  "single_leg_deadlift.png": require("@/assets/illustrations/single_leg_deadlift.png"),
  "single_leg_glute_bridges.png": require("@/assets/illustrations/single_leg_glute_bridges.png"),
  "single_leg_stand.png": require("@/assets/illustrations/single_leg_stand.png"),
  "soleus_stretch.png": require("@/assets/illustrations/soleus_stretch.png"),
  "spiderman_push_up_hold.png": require("@/assets/illustrations/spiderman_push_up_hold.png"),
  "spinal_twist.png": require("@/assets/illustrations/spinal_twist.png"),
  "split_lunge_hold.png": require("@/assets/illustrations/split_lunge_hold.png"),
  "split_squats.png": require("@/assets/illustrations/split_squats.png"),
  "squat_hold.png": require("@/assets/illustrations/squat_hold.png"),
  "squat_stretch.png": require("@/assets/illustrations/squat_stretch.png"),
  "standing_frog.png": require("@/assets/illustrations/standing_frog.png"),
  "standing_hip_openers.png": require("@/assets/illustrations/standing_hip_openers.png"),
  "standing_quad.png": require("@/assets/illustrations/standing_quad.png"),
  "sumo_squat_hold.png": require("@/assets/illustrations/sumo_squat_hold.png"),
  "superman.png": require("@/assets/illustrations/superman.png"),
  "thunderbolt.png": require("@/assets/illustrations/thunderbolt.png"),
  "toe_squat.png": require("@/assets/illustrations/toe_squat.png"),
  "toe_touch.png": require("@/assets/illustrations/toe_touch.png"),
  "toe_touch_hold.png": require("@/assets/illustrations/toe_touch_hold.png"),
  "toe_touch_twist.png": require("@/assets/illustrations/toe_touch_twist.png"),
  "trunk_rotation.png": require("@/assets/illustrations/trunk_rotation.png"),
  "trunk_twist.png": require("@/assets/illustrations/trunk_twist.png"),
  "twisted_sphinx.png": require("@/assets/illustrations/twisted_sphinx.png"),
  "upward_dog.png": require("@/assets/illustrations/upward_dog.png"),
  "upward_frog.png": require("@/assets/illustrations/upward_frog.png"),
  "upward_salute.png": require("@/assets/illustrations/upward_salute.png"),
  "v_sit.png": require("@/assets/illustrations/v_sit.png"),
  "wall_arms.png": require("@/assets/illustrations/wall_arms.png"),
  "wall_dog.png": require("@/assets/illustrations/wall_dog.png"),
  "wall_handstand.png": require("@/assets/illustrations/wall_handstand.png"),
  "wall_pecs.png": require("@/assets/illustrations/wall_pecs.png"),
  "wall_pike.png": require("@/assets/illustrations/wall_pike.png"),
  "wall_plank.png": require("@/assets/illustrations/wall_plank.png"),
  "wall_sit.png": require("@/assets/illustrations/wall_sit.png"),
  "wide_leg_bend.png": require("@/assets/illustrations/wide_leg_bend.png"),
  "wide_leg_side_bend.png": require("@/assets/illustrations/wide_leg_side_bend.png"),
  "wide_leg_toe_touches.png": require("@/assets/illustrations/wide_leg_toe_touches.png"),
  "wide_leg_torso_circles.png": require("@/assets/illustrations/wide_leg_torso_circles.png"),
  "wrist_circles.png": require("@/assets/illustrations/wrist_circles.png"),
  "wrist_extension.png": require("@/assets/illustrations/wrist_extension.png"),
  "wrist_flexion.png": require("@/assets/illustrations/wrist_flexion.png"),
  "zombie_walks.png": require("@/assets/illustrations/zombie_walks.png"),
};

export function getExerciseIllustration(iconFilename: string): ImageSourcePropType | null {
  return illustrations[iconFilename] ?? null;
}

/**
 * Pick a distinct representative icon for a routine.
 * Uses the exercise at the given offset (default middle) so that
 * routines sharing early exercises (like series) get different covers.
 */
export function getRoutineIcon(
  exercises: { exerciseId: string }[],
  getExercise: (id: string) => { iconFilename: string } | undefined,
  offset?: number,
): string | undefined {
  if (exercises.length === 0) return undefined;
  const idx = offset ?? Math.floor(exercises.length / 2);
  const safeIdx = Math.min(idx, exercises.length - 1);
  return getExercise(exercises[safeIdx].exerciseId)?.iconFilename;
}
