import type { Routine } from './types';

export const ALL_ROUTINES: Routine[] = [
  {
    id: "wake-and-shake-1",
    name: "Wake & Shake 1",
    description: "An energizing routine that uses dynamic stretches and mobility exercises to prime your body for an active, productive day ahead.",
    category: "energize",
    routineType: "dynamic",
    difficulty: "beginner",
    durationMinutes: 5,
    bodyAreas: [],
    exercises: [
      { exerciseId: "dynamic-side-bends", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "arm-circles", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "arm-swings", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "good-mornings", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "trunk-twist", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "neck-roll", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "hip-circles", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "dynamic-wide-leg-forward-fold", holdSeconds: 30, sides: "none", order: 8 },
    ],
    tags: ["energize","dynamic","beginner"],
  },
  {
    id: "wake-and-shake-2",
    name: "Wake & Shake 2",
    description: "An energizing routine that uses dynamic stretches and mobility exercises to prime your body for an active, productive day ahead.",
    category: "energize",
    routineType: "dynamic",
    difficulty: "intermediate",
    durationMinutes: 10,
    bodyAreas: [],
    exercises: [
      { exerciseId: "dynamic-side-bends", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "arm-circles", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "arm-swings", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "good-mornings", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "trunk-twist", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "neck-roll", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "hip-circles", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "hamstring-scoops", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "gate-opener", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "dynamic-wide-leg-forward-fold", holdSeconds: 30, sides: "none", order: 10 },
      { exerciseId: "wide-leg-torso-circles", holdSeconds: 30, sides: "both", order: 11 },
      { exerciseId: "knees-hugs", holdSeconds: 30, sides: "none", order: 12 },
      { exerciseId: "knee-circles", holdSeconds: 30, sides: "both", order: 13 },
    ],
    tags: ["energize","dynamic","intermediate"],
  },
  {
    id: "wake-and-shake-3",
    name: "Wake & Shake 3",
    description: "An energizing routine that uses dynamic stretches and mobility exercises to prime your body for an active, productive day ahead.",
    category: "energize",
    routineType: "dynamic",
    difficulty: "intermediate",
    durationMinutes: 15,
    bodyAreas: [],
    exercises: [
      { exerciseId: "dynamic-side-bends", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "arm-circles", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "arm-swings", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "good-mornings", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "trunk-twist", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "shoulder-rolls", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "neck-roll", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "hip-circles", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "hamstring-scoops", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "gate-opener", holdSeconds: 30, sides: "both", order: 10 },
      { exerciseId: "leg-swings", holdSeconds: 30, sides: "both", order: 11 },
      { exerciseId: "lateral-leg-swing", holdSeconds: 30, sides: "both", order: 12 },
      { exerciseId: "dynamic-wide-leg-forward-fold", holdSeconds: 30, sides: "none", order: 13 },
      { exerciseId: "wide-leg-torso-circles", holdSeconds: 30, sides: "both", order: 14 },
      { exerciseId: "toe-touch-twist", holdSeconds: 30, sides: "none", order: 15 },
      { exerciseId: "standing-hip-openers", holdSeconds: 30, sides: "none", order: 16 },
      { exerciseId: "high-knee-twists", holdSeconds: 30, sides: "none", order: 17 },
      { exerciseId: "knee-circles", holdSeconds: 30, sides: "both", order: 18 },
      { exerciseId: "ankle-circles", holdSeconds: 30, sides: "both", order: 19 },
      { exerciseId: "wrist-circles", holdSeconds: 30, sides: "none", order: 20 },
    ],
    tags: ["energize","dynamic","intermediate"],
  },
  {
    id: "tech-neck",
    name: "Tech Neck",
    description: "Fix rounded shoulders, forward head posture, and a curved upper spine with stretches that lengthen muscles in your chest, shoulders, and neck.",
    category: "posture",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: ["posture"],
    exercises: [
      { exerciseId: "chin-retractions", holdSeconds: 15, sides: "none", order: 1 },
      { exerciseId: "wall-pecs", holdSeconds: 60, sides: "both", order: 2 },
      { exerciseId: "upward-salute", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "chin-retractions", holdSeconds: 15, sides: "none", order: 4 },
      { exerciseId: "wall-dog", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "doorway-pecs", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "one-arm-hug", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "reverse-shoulder", holdSeconds: 30, sides: "none", order: 8 },
      { exerciseId: "neck-laterals", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "chin-retractions", holdSeconds: 15, sides: "none", order: 10 },
    ],
    tags: ["posture","stretching","beginner","posture"],
  },
  {
    id: "pelvic-tilt",
    name: "Pelvic Tilt",
    description: "Undo anterior pelvic tilt and an arched lower back with stretches that lengthen muscles in your lower back and hip flexors.",
    category: "posture",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 10,
    bodyAreas: ["core","posture"],
    exercises: [
      { exerciseId: "pelvic-tilt-press", holdSeconds: 38, sides: "none", order: 1 },
      { exerciseId: "pelvic-tilt-press", holdSeconds: 38, sides: "none", order: 2 },
      { exerciseId: "butterfly", holdSeconds: 38, sides: "none", order: 3 },
      { exerciseId: "cat-cow", holdSeconds: 38, sides: "none", order: 4 },
      { exerciseId: "knees-to-chest", holdSeconds: 38, sides: "none", order: 5 },
      { exerciseId: "lunge", holdSeconds: 38, sides: "both", order: 6 },
      { exerciseId: "lying-figure-four", holdSeconds: 38, sides: "both", order: 7 },
      { exerciseId: "lying-quad-stretch", holdSeconds: 38, sides: "both", order: 8 },
      { exerciseId: "single-knee-to-chest", holdSeconds: 38, sides: "both", order: 9 },
      { exerciseId: "bridge", holdSeconds: 38, sides: "none", order: 10 },
      { exerciseId: "bridge", holdSeconds: 38, sides: "none", order: 11 },
    ],
    tags: ["posture","stretching","intermediate","core","posture"],
  },
  {
    id: "posture-stabilizer",
    name: "Posture Stabilizer",
    description: "A series of planks and isometric exercises that improve posture by strengthening muscles in the core and back.",
    category: "posture",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: ["posture"],
    exercises: [
      { exerciseId: "crunch-hold", holdSeconds: 15, sides: "none", order: 1 },
      { exerciseId: "bridge", holdSeconds: 15, sides: "none", order: 2 },
      { exerciseId: "dead-bug", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "bridge-leg-lift", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "bicycle-crunch-hold", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "bird-dog", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "airplane", holdSeconds: 15, sides: "none", order: 7 },
      { exerciseId: "lying-side-leg-raise", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "hand-plank", holdSeconds: 15, sides: "none", order: 10 },
    ],
    tags: ["posture","strength","beginner","posture"],
  },
  {
    id: "posture-power",
    name: "Posture Power",
    description: "A series of squats and lunge holds designed to strengthen the muscles in your legs, core, and back.",
    category: "posture",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 5,
    bodyAreas: ["posture"],
    exercises: [
      { exerciseId: "squat-hold", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "split-lunge-hold", holdSeconds: 60, sides: "both", order: 2 },
      { exerciseId: "side-lunge-hold", holdSeconds: 60, sides: "both", order: 3 },
      { exerciseId: "wall-sit", holdSeconds: 30, sides: "none", order: 4 },
    ],
    tags: ["posture","strength","beginner","posture"],
  },
  {
    id: "sleep",
    name: "Sleep",
    description: "Unwind and de-stress with gentle, long-hold stretches designed to improve sleep quality.",
    category: "relax-unwind",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 12,
    bodyAreas: [],
    exercises: [
      { exerciseId: "rag-doll", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "upward-dog", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "childs-pose", holdSeconds: 60, sides: "none", order: 3 },
      { exerciseId: "knees-to-chest", holdSeconds: 60, sides: "none", order: 4 },
      { exerciseId: "happy-baby", holdSeconds: 60, sides: "none", order: 5 },
      { exerciseId: "reclined-butterfly", holdSeconds: 60, sides: "none", order: 6 },
      { exerciseId: "spinal-twist", holdSeconds: 60, sides: "both", order: 7 },
      { exerciseId: "quad-stretch", holdSeconds: 60, sides: "both", order: 8 },
      { exerciseId: "legs-up-wall", holdSeconds: 120, sides: "none", order: 9 },
    ],
    tags: ["relax-unwind","stretching","intermediate"],
  },
  {
    id: "detox",
    name: "Detox",
    description: "A series of detoxifying movements and twists that will compress and release organs.",
    category: "relax-unwind",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 10,
    bodyAreas: [],
    exercises: [
      { exerciseId: "wide-leg-bend", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "upward-dog", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "downward-dog", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "cat-cow", holdSeconds: 60, sides: "none", order: 4 },
      { exerciseId: "seated-twist", holdSeconds: 60, sides: "both", order: 5 },
      { exerciseId: "spinal-twist", holdSeconds: 60, sides: "both", order: 6 },
      { exerciseId: "locust-pose", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "shoulder-stand", holdSeconds: 60, sides: "none", order: 8 },
      { exerciseId: "plow", holdSeconds: 60, sides: "none", order: 9 },
    ],
    tags: ["relax-unwind","stretching","intermediate"],
  },
  {
    id: "deep-relax",
    name: "Deep Relax",
    description: "Activate your parasympathetic nervous system and alleviate stress with relaxing, long-hold stretches.",
    category: "relax-unwind",
    routineType: "restorative",
    difficulty: "expert",
    durationMinutes: 26,
    bodyAreas: [],
    exercises: [
      { exerciseId: "upward-salute", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "rag-doll", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "upward-dog", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "childs-pose", holdSeconds: 60, sides: "none", order: 4 },
      { exerciseId: "knees-to-chest", holdSeconds: 120, sides: "none", order: 5 },
      { exerciseId: "lying-figure-four", holdSeconds: 120, sides: "both", order: 6 },
      { exerciseId: "spinal-twist", holdSeconds: 120, sides: "both", order: 7 },
      { exerciseId: "quad-stretch", holdSeconds: 120, sides: "both", order: 8 },
      { exerciseId: "seated-fold", holdSeconds: 60, sides: "none", order: 9 },
      { exerciseId: "butterfly", holdSeconds: 60, sides: "none", order: 10 },
      { exerciseId: "folded-butterfly", holdSeconds: 60, sides: "none", order: 11 },
      { exerciseId: "happy-baby", holdSeconds: 60, sides: "none", order: 12 },
      { exerciseId: "plow", holdSeconds: 60, sides: "none", order: 13 },
      { exerciseId: "reclined-butterfly", holdSeconds: 120, sides: "none", order: 14 },
      { exerciseId: "legs-up-wall", holdSeconds: 120, sides: "none", order: 15 },
    ],
    tags: ["relax-unwind","restorative","expert"],
  },
  {
    id: "posture-reset",
    name: "Posture Reset",
    description: "Improve your posture with seated stretches designed to correct habitual posture problems.",
    category: "at-the-office",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 6,
    bodyAreas: ["posture"],
    exercises: [
      { exerciseId: "shoulder-rolls", holdSeconds: 30, sides: "both", order: 1 },
      { exerciseId: "overhead-reach", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "side-bend", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "cactus-arms", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "neck-flex", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "neck-roll", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "neck-laterals", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "diver", holdSeconds: 30, sides: "none", order: 8 },
    ],
    tags: ["at-the-office","stretching","beginner","posture"],
  },
  {
    id: "desk-stretch",
    name: "Desk Stretch",
    description: "Break up the work day with a refreshing, full-body routine that can be done right from your desk.",
    category: "at-the-office",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 10,
    bodyAreas: [],
    exercises: [
      { exerciseId: "seated-figure-four", holdSeconds: 60, sides: "both", order: 1 },
      { exerciseId: "seated-hamstring", holdSeconds: 60, sides: "both", order: 2 },
      { exerciseId: "trunk-rotation", holdSeconds: 60, sides: "both", order: 3 },
      { exerciseId: "chest-opener", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "one-arm-hug", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "overhead-tricep", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "forearm-stretch", holdSeconds: 60, sides: "both", order: 7 },
    ],
    tags: ["at-the-office","stretching","intermediate"],
  },
  {
    id: "standing-desk",
    name: "Standing Desk",
    description: "A quick series of standing stretches focused on reducing tightness in shoulders, lower back, and neck.",
    category: "at-the-office",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 8,
    bodyAreas: [],
    exercises: [
      { exerciseId: "upward-salute", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "toe-touch", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "chest-opener", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "one-arm-hug", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "overhead-tricep", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "wall-dog", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "standing-quad", holdSeconds: 60, sides: "both", order: 7 },
      { exerciseId: "leaning-calf", holdSeconds: 60, sides: "both", order: 8 },
      { exerciseId: "rag-doll", holdSeconds: 30, sides: "none", order: 9 },
    ],
    tags: ["at-the-office","stretching","intermediate"],
  },
  {
    id: "pre-run-2",
    name: "Pre-Run 2",
    description: "An energizing warm-up sequence of dynamic stretches and mobility drills.",
    category: "running",
    routineType: "dynamic",
    difficulty: "intermediate",
    durationMinutes: 12,
    bodyAreas: [],
    exercises: [
      { exerciseId: "arm-circles", holdSeconds: 28, sides: "both", order: 1 },
      { exerciseId: "butt-kicks", holdSeconds: 28, sides: "none", order: 2 },
      { exerciseId: "dynamic-quad-stretch", holdSeconds: 28, sides: "both", order: 3 },
      { exerciseId: "dynamic-side-bends", holdSeconds: 28, sides: "none", order: 4 },
      { exerciseId: "gate-opener", holdSeconds: 28, sides: "both", order: 5 },
      { exerciseId: "hamstring-scoops", holdSeconds: 28, sides: "both", order: 6 },
      { exerciseId: "heel-to-toe-rocks", holdSeconds: 28, sides: "none", order: 7 },
      { exerciseId: "high-knee-twists", holdSeconds: 28, sides: "none", order: 8 },
      { exerciseId: "high-knees", holdSeconds: 28, sides: "none", order: 9 },
      { exerciseId: "knee-circles", holdSeconds: 28, sides: "both", order: 10 },
      { exerciseId: "lateral-foot-rocks", holdSeconds: 28, sides: "none", order: 11 },
      { exerciseId: "lateral-leg-swing", holdSeconds: 28, sides: "both", order: 12 },
      { exerciseId: "lateral-lunge", holdSeconds: 28, sides: "none", order: 13 },
      { exerciseId: "leg-swings", holdSeconds: 28, sides: "both", order: 14 },
      { exerciseId: "runners-lunge-twist", holdSeconds: 28, sides: "both", order: 15 },
      { exerciseId: "split-squats", holdSeconds: 28, sides: "both", order: 16 },
      { exerciseId: "toe-touch-twist", holdSeconds: 28, sides: "none", order: 17 },
    ],
    tags: ["running","dynamic","intermediate"],
  },
  {
    id: "post-run-1",
    name: "Post-Run 1",
    description: "Improve your stride, speed, and recovery with post-run stretches.",
    category: "running",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 10,
    bodyAreas: [],
    exercises: [
      { exerciseId: "cross-leg-fold", holdSeconds: 60, sides: "both", order: 1 },
      { exerciseId: "hurdler", holdSeconds: 60, sides: "both", order: 2 },
      { exerciseId: "lunge", holdSeconds: 60, sides: "both", order: 3 },
      { exerciseId: "lying-figure-four", holdSeconds: 60, sides: "both", order: 4 },
      { exerciseId: "standing-quad", holdSeconds: 60, sides: "both", order: 5 },
    ],
    tags: ["running","stretching","beginner"],
  },
  {
    id: "post-run-2",
    name: "Post-Run 2",
    description: "An energizing warm-up sequence of dynamic stretches and mobility drills.",
    category: "running",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 14,
    bodyAreas: [],
    exercises: [
      { exerciseId: "leaning-calf", holdSeconds: 70, sides: "both", order: 1 },
      { exerciseId: "lunge", holdSeconds: 70, sides: "both", order: 2 },
      { exerciseId: "lying-figure-four", holdSeconds: 70, sides: "both", order: 3 },
      { exerciseId: "lying-hamstring", holdSeconds: 70, sides: "both", order: 4 },
      { exerciseId: "side-lunge", holdSeconds: 70, sides: "both", order: 5 },
      { exerciseId: "standing-quad", holdSeconds: 70, sides: "both", order: 6 },
    ],
    tags: ["running","stretching","intermediate"],
  },
  {
    id: "post-run-3",
    name: "Post-Run 3",
    description: "An energizing warm-up sequence of dynamic stretches and mobility drills.",
    category: "running",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 18,
    bodyAreas: [],
    exercises: [
      { exerciseId: "bent-over-calf", holdSeconds: 50, sides: "both", order: 1 },
      { exerciseId: "butterfly", holdSeconds: 50, sides: "none", order: 2 },
      { exerciseId: "cross-leg-fold", holdSeconds: 50, sides: "both", order: 3 },
      { exerciseId: "downward-dog", holdSeconds: 50, sides: "none", order: 4 },
      { exerciseId: "hurdler", holdSeconds: 50, sides: "both", order: 5 },
      { exerciseId: "leaning-calf", holdSeconds: 50, sides: "both", order: 6 },
      { exerciseId: "lunge", holdSeconds: 50, sides: "both", order: 7 },
      { exerciseId: "modified-seated-twist", holdSeconds: 50, sides: "both", order: 8 },
      { exerciseId: "pigeon", holdSeconds: 50, sides: "both", order: 9 },
      { exerciseId: "reverse-lunge", holdSeconds: 50, sides: "both", order: 10 },
      { exerciseId: "standing-quad", holdSeconds: 50, sides: "both", order: 11 },
      { exerciseId: "wide-leg-side-bend", holdSeconds: 50, sides: "both", order: 12 },
    ],
    tags: ["running","stretching","intermediate"],
  },
  {
    id: "front-splits-warm-up",
    name: "Front Splits Warm Up",
    description: "Activate and prepare your legs, hips, and lower back with gentle dynamic moves.",
    category: "splits",
    routineType: "dynamic",
    difficulty: "beginner",
    durationMinutes: 4,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "dynamic-wide-leg-forward-fold", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "gate-opener", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "hamstring-scoops", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "leg-swings", holdSeconds: 30, sides: "both", order: 4 },
    ],
    tags: ["splits","dynamic","beginner","splits"],
  },
  {
    id: "front-splits-1",
    name: "Front Splits 1",
    description: "A series of static stretches designed to gradually lengthen hip flexors, hamstrings, and inner thighs.",
    category: "splits",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 9,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "hurdler", holdSeconds: 50, sides: "both", order: 1 },
      { exerciseId: "lizard-pose", holdSeconds: 50, sides: "both", order: 2 },
      { exerciseId: "lunge", holdSeconds: 50, sides: "both", order: 3 },
      { exerciseId: "quad-stretch", holdSeconds: 50, sides: "both", order: 4 },
      { exerciseId: "reverse-lunge", holdSeconds: 50, sides: "both", order: 5 },
      { exerciseId: "seated-fold", holdSeconds: 50, sides: "none", order: 6 },
    ],
    tags: ["splits","stretching","beginner","splits"],
  },
  {
    id: "front-splits-2",
    name: "Front Splits 2",
    description: "Activate and prepare your legs, hips, and lower back with gentle dynamic moves.",
    category: "splits",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 18,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "bent-over-calf", holdSeconds: 50, sides: "both", order: 1 },
      { exerciseId: "front-split", holdSeconds: 50, sides: "both", order: 2 },
      { exerciseId: "hurdler", holdSeconds: 50, sides: "both", order: 3 },
      { exerciseId: "kneeling-quad", holdSeconds: 50, sides: "both", order: 4 },
      { exerciseId: "lizard-pose", holdSeconds: 50, sides: "both", order: 5 },
      { exerciseId: "lunge", holdSeconds: 50, sides: "both", order: 6 },
      { exerciseId: "pigeon", holdSeconds: 50, sides: "both", order: 7 },
      { exerciseId: "quad-stretch", holdSeconds: 50, sides: "both", order: 8 },
      { exerciseId: "reverse-lunge", holdSeconds: 50, sides: "both", order: 9 },
      { exerciseId: "seated-fold", holdSeconds: 50, sides: "none", order: 10 },
      { exerciseId: "toe-touch", holdSeconds: 50, sides: "none", order: 11 },
      { exerciseId: "wide-leg-bend", holdSeconds: 50, sides: "none", order: 12 },
    ],
    tags: ["splits","stretching","intermediate","splits"],
  },
  {
    id: "front-splits-3",
    name: "Front Splits 3",
    description: "Activate and prepare your legs, hips, and lower back with gentle dynamic moves.",
    category: "splits",
    routineType: "stretching",
    difficulty: "expert",
    durationMinutes: 28,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "bent-over-calf", holdSeconds: 56, sides: "both", order: 1 },
      { exerciseId: "cross-leg-fold", holdSeconds: 56, sides: "both", order: 2 },
      { exerciseId: "deep-split-squat", holdSeconds: 56, sides: "both", order: 3 },
      { exerciseId: "front-split", holdSeconds: 56, sides: "both", order: 4 },
      { exerciseId: "hurdler", holdSeconds: 56, sides: "both", order: 5 },
      { exerciseId: "kneeling-quad", holdSeconds: 56, sides: "both", order: 6 },
      { exerciseId: "lizard-pose", holdSeconds: 56, sides: "both", order: 7 },
      { exerciseId: "lunge", holdSeconds: 56, sides: "both", order: 8 },
      { exerciseId: "lying-figure-four", holdSeconds: 56, sides: "both", order: 9 },
      { exerciseId: "pigeon", holdSeconds: 56, sides: "both", order: 10 },
      { exerciseId: "quad-stretch", holdSeconds: 56, sides: "both", order: 11 },
      { exerciseId: "reverse-lunge", holdSeconds: 56, sides: "both", order: 12 },
      { exerciseId: "seated-fold", holdSeconds: 56, sides: "none", order: 13 },
      { exerciseId: "side-lunge", holdSeconds: 56, sides: "both", order: 14 },
      { exerciseId: "standing-quad", holdSeconds: 56, sides: "both", order: 15 },
      { exerciseId: "wide-leg-bend", holdSeconds: 56, sides: "none", order: 16 },
    ],
    tags: ["splits","stretching","expert","splits"],
  },
  {
    id: "front-splits-mobility",
    name: "Front Splits Mobility",
    description: "Focus on dynamic stretches and mobility exercises to enhance joint resilience.",
    category: "splits",
    routineType: "dynamic",
    difficulty: "intermediate",
    durationMinutes: 9,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "90-90-hip-switch", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "90-90-hip-switch-no-hands", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "dynamic-quad-stretch", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "dynamic-wide-leg-forward-fold", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "gate-opener", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "hamstring-scoops", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "kneeling-hip-circles", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "knees-hugs", holdSeconds: 30, sides: "none", order: 8 },
      { exerciseId: "lateral-leg-swing", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "leg-swings", holdSeconds: 30, sides: "both", order: 10 },
      { exerciseId: "wide-leg-toe-touches", holdSeconds: 30, sides: "none", order: 11 },
      { exerciseId: "zombie-walks", holdSeconds: 30, sides: "none", order: 12 },
    ],
    tags: ["splits","dynamic","intermediate","splits"],
  },
  {
    id: "front-splits-strength",
    name: "Front Splits Strength",
    description: "Utilize isometric and calisthenic exercises to build supportive strength.",
    category: "splits",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 8,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "runners-lunge-twist", holdSeconds: 30, sides: "both", order: 1 },
      { exerciseId: "split-squats", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "90-90-hip-switch-extension", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "air-squats", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "bridge", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "side-lunge-hold", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "single-leg-deadlift", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "single-leg-glute-bridges", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "split-lunge-hold", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "squat-hold", holdSeconds: 30, sides: "none", order: 10 },
    ],
    tags: ["splits","strength","beginner","splits"],
  },
  {
    id: "warm-up",
    name: "Warm Up",
    description: "Prepare your body for physical activity with dynamic movements.",
    category: "pre-post-workout",
    routineType: "dynamic",
    difficulty: "beginner",
    durationMinutes: 6,
    bodyAreas: [],
    exercises: [
      { exerciseId: "jumping-jacks", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "air-squats", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "lateral-lunge", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "arm-circles", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "arm-swings", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "trunk-twist", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "toe-touch-twist", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "knees-hugs", holdSeconds: 30, sides: "none", order: 8 },
      { exerciseId: "leg-swings", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "knee-circles", holdSeconds: 30, sides: "both", order: 10 },
    ],
    tags: ["pre-post-workout","dynamic","beginner"],
  },
  {
    id: "cool-down",
    name: "Cool Down",
    description: "Light, easy stretches while your body transitions to a resting state.",
    category: "pre-post-workout",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 10,
    bodyAreas: [],
    exercises: [
      { exerciseId: "upward-salute", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "toe-touch", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "upward-dog", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "childs-pose", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "knees-to-chest", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "lying-figure-four", holdSeconds: 60, sides: "both", order: 6 },
      { exerciseId: "reclined-butterfly", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "spinal-twist", holdSeconds: 60, sides: "both", order: 8 },
      { exerciseId: "quad-stretch", holdSeconds: 60, sides: "both", order: 9 },
      { exerciseId: "butterfly", holdSeconds: 30, sides: "none", order: 10 },
      { exerciseId: "seated-fold", holdSeconds: 30, sides: "none", order: 11 },
      { exerciseId: "plow", holdSeconds: 30, sides: "none", order: 12 },
    ],
    tags: ["pre-post-workout","stretching","intermediate"],
  },
  {
    id: "strength-back",
    name: "Strength Back",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 4,
    bodyAreas: [],
    exercises: [
      { exerciseId: "airplane", holdSeconds: 45, sides: "none", order: 1 },
      { exerciseId: "aquaman", holdSeconds: 45, sides: "both", order: 2 },
      { exerciseId: "bird-dog", holdSeconds: 45, sides: "both", order: 3 },
      { exerciseId: "superman", holdSeconds: 45, sides: "none", order: 4 },
    ],
    tags: ["strength","strength","beginner"],
  },
  {
    id: "strength-abs",
    name: "Strength Abs",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 6,
    bodyAreas: [],
    exercises: [
      { exerciseId: "bicycle-crunch-hold", holdSeconds: 30, sides: "both", order: 1 },
      { exerciseId: "crunch-hold", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "dead-bug", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "hollow-body", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "leg-lift", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "lying-side-leg-raise", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "toe-touch-hold", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "v-sit", holdSeconds: 30, sides: "none", order: 8 },
    ],
    tags: ["strength","strength","beginner"],
  },
  {
    id: "strength-arms",
    name: "Strength Arms",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 4,
    bodyAreas: [],
    exercises: [
      { exerciseId: "bent-arm-pike", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "dip-hold", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "narrow-push-up-hold", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "pike", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "push-up-hold", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "reverse-plank", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "single-arm-plank", holdSeconds: 30, sides: "both", order: 8 },
    ],
    tags: ["strength","strength","beginner"],
  },
  {
    id: "strength-squats",
    name: "Strength Squats",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "intermediate",
    durationMinutes: 8,
    bodyAreas: [],
    exercises: [
      { exerciseId: "curtsy-lunge-hold", holdSeconds: 51, sides: "both", order: 1 },
      { exerciseId: "narrow-squat-hold", holdSeconds: 51, sides: "none", order: 2 },
      { exerciseId: "side-lunge-hold", holdSeconds: 51, sides: "both", order: 3 },
      { exerciseId: "split-lunge-hold", holdSeconds: 51, sides: "both", order: 4 },
      { exerciseId: "squat-hold", holdSeconds: 51, sides: "none", order: 5 },
      { exerciseId: "sumo-squat-hold", holdSeconds: 51, sides: "none", order: 6 },
      { exerciseId: "wall-sit", holdSeconds: 51, sides: "none", order: 7 },
    ],
    tags: ["strength","strength","intermediate"],
  },
  {
    id: "strength-core",
    name: "Strength Core",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "intermediate",
    durationMinutes: 8,
    bodyAreas: [],
    exercises: [
      { exerciseId: "bicycle-crunch-hold", holdSeconds: 30, sides: "both", order: 1 },
      { exerciseId: "bridge", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "elbow-pike", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "elbow-plank", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "leg-lift", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "lying-side-leg-raise", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "reverse-plank", holdSeconds: 30, sides: "none", order: 9 },
      { exerciseId: "reverse-plank-leg-lift", holdSeconds: 30, sides: "both", order: 10 },
      { exerciseId: "superman", holdSeconds: 30, sides: "none", order: 11 },
      { exerciseId: "toe-touch-hold", holdSeconds: 30, sides: "none", order: 12 },
    ],
    tags: ["strength","strength","intermediate"],
  },
  {
    id: "strength-full-body",
    name: "Strength Full Body",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "intermediate",
    durationMinutes: 16,
    bodyAreas: [],
    exercises: [
      { exerciseId: "airplane", holdSeconds: 31, sides: "none", order: 1 },
      { exerciseId: "bent-arm-pike", holdSeconds: 31, sides: "none", order: 2 },
      { exerciseId: "bicycle-crunch-hold", holdSeconds: 31, sides: "both", order: 3 },
      { exerciseId: "bridge", holdSeconds: 31, sides: "none", order: 4 },
      { exerciseId: "bridge-leg-lift", holdSeconds: 31, sides: "both", order: 5 },
      { exerciseId: "bulldog", holdSeconds: 31, sides: "none", order: 6 },
      { exerciseId: "crunch-hold", holdSeconds: 31, sides: "none", order: 7 },
      { exerciseId: "dip-hold", holdSeconds: 31, sides: "none", order: 8 },
      { exerciseId: "elbow-side-plank", holdSeconds: 31, sides: "both", order: 9 },
      { exerciseId: "hand-plank", holdSeconds: 31, sides: "none", order: 10 },
      { exerciseId: "hand-plank-leg-lift", holdSeconds: 31, sides: "both", order: 11 },
      { exerciseId: "hand-side-plank", holdSeconds: 31, sides: "both", order: 12 },
      { exerciseId: "hollow-body", holdSeconds: 31, sides: "none", order: 13 },
      { exerciseId: "lying-side-leg-raise", holdSeconds: 31, sides: "both", order: 14 },
      { exerciseId: "narrow-squat-hold", holdSeconds: 31, sides: "none", order: 15 },
      { exerciseId: "pike", holdSeconds: 31, sides: "none", order: 16 },
      { exerciseId: "push-up-hold", holdSeconds: 31, sides: "none", order: 17 },
      { exerciseId: "side-lunge-hold", holdSeconds: 31, sides: "both", order: 18 },
      { exerciseId: "split-lunge-hold", holdSeconds: 31, sides: "both", order: 19 },
      { exerciseId: "squat-hold", holdSeconds: 31, sides: "none", order: 20 },
      { exerciseId: "sumo-squat-hold", holdSeconds: 31, sides: "none", order: 21 },
      { exerciseId: "superman", holdSeconds: 31, sides: "none", order: 22 },
      { exerciseId: "toe-touch-hold", holdSeconds: 31, sides: "none", order: 23 },
    ],
    tags: ["strength","strength","intermediate"],
  },
  {
    id: "strength-expert",
    name: "Strength Expert",
    description: "An isometric exercise routine that builds muscle, strength, balance, and range of motion.",
    category: "strength",
    routineType: "strength",
    difficulty: "expert",
    durationMinutes: 37,
    bodyAreas: [],
    exercises: [
      { exerciseId: "squat-hold", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "narrow-squat-hold", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "sumo-squat-hold", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "split-lunge-hold", holdSeconds: 60, sides: "both", order: 4 },
      { exerciseId: "side-lunge-hold", holdSeconds: 60, sides: "both", order: 5 },
      { exerciseId: "curtsy-lunge-hold", holdSeconds: 60, sides: "both", order: 6 },
      { exerciseId: "pistol-squat-hold", holdSeconds: 60, sides: "both", order: 7 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 8 },
      { exerciseId: "hand-plank-leg-lift", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "hand-side-plank", holdSeconds: 30, sides: "both", order: 10 },
      { exerciseId: "hand-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 11 },
      { exerciseId: "elbow-plank", holdSeconds: 30, sides: "none", order: 12 },
      { exerciseId: "elbow-plank-leg-lift", holdSeconds: 30, sides: "both", order: 13 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 14 },
      { exerciseId: "elbow-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 15 },
      { exerciseId: "single-arm-plank", holdSeconds: 30, sides: "both", order: 16 },
      { exerciseId: "bulldog", holdSeconds: 30, sides: "none", order: 17 },
      { exerciseId: "bird-dog", holdSeconds: 30, sides: "both", order: 18 },
      { exerciseId: "bird-dog-plank", holdSeconds: 30, sides: "both", order: 19 },
      { exerciseId: "push-up-hold", holdSeconds: 30, sides: "none", order: 20 },
      { exerciseId: "narrow-push-up-hold", holdSeconds: 30, sides: "none", order: 21 },
      { exerciseId: "spiderman-push-up-hold", holdSeconds: 30, sides: "both", order: 22 },
      { exerciseId: "bridge", holdSeconds: 30, sides: "none", order: 23 },
      { exerciseId: "bridge-leg-lift", holdSeconds: 30, sides: "both", order: 24 },
      { exerciseId: "reverse-plank", holdSeconds: 30, sides: "none", order: 25 },
      { exerciseId: "reverse-plank-leg-lift", holdSeconds: 30, sides: "both", order: 26 },
      { exerciseId: "crunch-hold", holdSeconds: 30, sides: "none", order: 27 },
      { exerciseId: "bicycle-crunch-hold", holdSeconds: 60, sides: "both", order: 28 },
      { exerciseId: "toe-touch-hold", holdSeconds: 30, sides: "none", order: 29 },
      { exerciseId: "v-sit", holdSeconds: 30, sides: "none", order: 30 },
      { exerciseId: "leg-lift", holdSeconds: 30, sides: "none", order: 31 },
      { exerciseId: "hollow-body", holdSeconds: 30, sides: "none", order: 32 },
      { exerciseId: "dead-bug", holdSeconds: 60, sides: "both", order: 33 },
      { exerciseId: "superman", holdSeconds: 30, sides: "none", order: 34 },
      { exerciseId: "aquaman", holdSeconds: 60, sides: "both", order: 35 },
      { exerciseId: "airplane", holdSeconds: 30, sides: "none", order: 36 },
      { exerciseId: "pike", holdSeconds: 30, sides: "none", order: 37 },
      { exerciseId: "bent-arm-pike", holdSeconds: 30, sides: "none", order: 38 },
      { exerciseId: "wall-plank", holdSeconds: 30, sides: "none", order: 39 },
      { exerciseId: "wall-pike", holdSeconds: 30, sides: "none", order: 40 },
      { exerciseId: "wall-handstand", holdSeconds: 30, sides: "none", order: 41 },
    ],
    tags: ["strength","strength","expert"],
  },
  {
    id: "planks-1",
    name: "Planks 1",
    description: "A series of plank poses activating all of the muscles in your core.",
    category: "planks",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 3,
    bodyAreas: [],
    exercises: [
      { exerciseId: "elbow-plank", holdSeconds: 40, sides: "none", order: 1 },
      { exerciseId: "elbow-side-plank", holdSeconds: 40, sides: "both", order: 2 },
      { exerciseId: "hand-plank", holdSeconds: 40, sides: "none", order: 3 },
    ],
    tags: ["planks","strength","beginner"],
  },
  {
    id: "planks-2",
    name: "Planks 2",
    description: "A series of plank poses activating all of the muscles in your core.",
    category: "planks",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 5,
    bodyAreas: [],
    exercises: [
      { exerciseId: "elbow-plank", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "elbow-plank-leg-lift", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "hand-plank-leg-lift", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "hand-side-plank", holdSeconds: 30, sides: "both", order: 6 },
    ],
    tags: ["planks","strength","beginner"],
  },
  {
    id: "planks-3",
    name: "Planks 3",
    description: "A series of plank poses activating all of the muscles in your core.",
    category: "planks",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: [],
    exercises: [
      { exerciseId: "elbow-plank", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "elbow-plank-leg-lift", holdSeconds: 30, sides: "both", order: 2 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "elbow-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 5 },
      { exerciseId: "hand-plank-leg-lift", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "hand-side-plank", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "hand-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 8 },
    ],
    tags: ["planks","strength","beginner"],
  },
  {
    id: "planks-4",
    name: "Planks 4",
    description: "A series of plank poses activating all of the muscles in your core.",
    category: "planks",
    routineType: "strength",
    difficulty: "beginner",
    durationMinutes: 9,
    bodyAreas: [],
    exercises: [
      { exerciseId: "bird-dog-plank", holdSeconds: 30, sides: "both", order: 1 },
      { exerciseId: "elbow-plank", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "elbow-plank-leg-lift", holdSeconds: 30, sides: "both", order: 3 },
      { exerciseId: "elbow-side-plank", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "elbow-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "hand-plank", holdSeconds: 30, sides: "none", order: 6 },
      { exerciseId: "hand-plank-leg-lift", holdSeconds: 30, sides: "both", order: 7 },
      { exerciseId: "hand-side-plank", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "hand-side-plank-leg-lift", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "single-arm-plank", holdSeconds: 30, sides: "both", order: 10 },
    ],
    tags: ["planks","strength","beginner"],
  },
  {
    id: "targeted-shoulders",
    name: "Targeted Shoulders",
    description: "Achieve a full range of motion in your shoulders with long-hold stretches.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "intermediate",
    durationMinutes: 17,
    bodyAreas: ["shoulders"],
    exercises: [
      { exerciseId: "upward-salute", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "chest-opener", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "overhead-tricep", holdSeconds: 60, sides: "both", order: 3 },
      { exerciseId: "one-arm-hug", holdSeconds: 60, sides: "both", order: 4 },
      { exerciseId: "wall-dog", holdSeconds: 60, sides: "none", order: 5 },
      { exerciseId: "forward-fold", holdSeconds: 60, sides: "none", order: 6 },
      { exerciseId: "shoulder-cross", holdSeconds: 120, sides: "both", order: 7 },
      { exerciseId: "shoulder-opener", holdSeconds: 120, sides: "both", order: 8 },
      { exerciseId: "childs-pose", holdSeconds: 60, sides: "none", order: 9 },
    ],
    tags: ["targeted","deep-stretch","intermediate","shoulders"],
  },
  {
    id: "targeted-twists-and-wrists",
    name: "Targeted Twists & Wrists",
    description: "Twisting actions targeting the spine combined with wrist and ankle stretches.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "intermediate",
    durationMinutes: 15,
    bodyAreas: [],
    exercises: [
      { exerciseId: "rag-doll", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "forward-fold", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "upward-dog", holdSeconds: 60, sides: "none", order: 3 },
      { exerciseId: "twisted-sphinx", holdSeconds: 120, sides: "both", order: 4 },
      { exerciseId: "seated-twist", holdSeconds: 60, sides: "both", order: 5 },
      { exerciseId: "toe-squat", holdSeconds: 60, sides: "none", order: 6 },
      { exerciseId: "wrist-extension", holdSeconds: 60, sides: "none", order: 7 },
      { exerciseId: "wrist-flexion", holdSeconds: 60, sides: "none", order: 8 },
      { exerciseId: "spinal-twist", holdSeconds: 60, sides: "both", order: 9 },
      { exerciseId: "plow", holdSeconds: 60, sides: "none", order: 10 },
    ],
    tags: ["targeted","deep-stretch","intermediate"],
  },
  {
    id: "targeted-hamstrings",
    name: "Targeted Hamstrings",
    description: "Improve hamstring flexibility with subtle stretches.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "intermediate",
    durationMinutes: 20,
    bodyAreas: ["hamstrings"],
    exercises: [
      { exerciseId: "rag-doll", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "wide-leg-bend", holdSeconds: 60, sides: "none", order: 2 },
      { exerciseId: "side-lunge", holdSeconds: 120, sides: "both", order: 3 },
      { exerciseId: "reverse-lunge", holdSeconds: 120, sides: "both", order: 4 },
      { exerciseId: "seated-fold", holdSeconds: 60, sides: "none", order: 5 },
      { exerciseId: "hurdler", holdSeconds: 120, sides: "both", order: 6 },
      { exerciseId: "seated-straddle", holdSeconds: 60, sides: "none", order: 7 },
      { exerciseId: "hamstring-pulls", holdSeconds: 120, sides: "both", order: 8 },
    ],
    tags: ["targeted","deep-stretch","intermediate","hamstrings"],
  },
  {
    id: "targeted-hips",
    name: "Targeted Hips",
    description: "Open and unlock tight hips with deep, focused stretches.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "expert",
    durationMinutes: 21,
    bodyAreas: ["hips"],
    exercises: [
      { exerciseId: "lizard-pose", holdSeconds: 120, sides: "both", order: 1 },
      { exerciseId: "pigeon", holdSeconds: 120, sides: "both", order: 2 },
      { exerciseId: "folded-butterfly", holdSeconds: 60, sides: "none", order: 3 },
      { exerciseId: "happy-baby", holdSeconds: 60, sides: "none", order: 4 },
      { exerciseId: "lying-figure-four", holdSeconds: 120, sides: "both", order: 5 },
      { exerciseId: "frog-pose", holdSeconds: 60, sides: "none", order: 6 },
      { exerciseId: "squat-stretch", holdSeconds: 60, sides: "none", order: 7 },
      { exerciseId: "double-pigeon", holdSeconds: 120, sides: "both", order: 8 },
      { exerciseId: "reclined-butterfly", holdSeconds: 60, sides: "none", order: 9 },
    ],
    tags: ["targeted","deep-stretch","expert","hips"],
  },
  {
    id: "targeted-lower-back",
    name: "Targeted Lower Back",
    description: "A series of stretches designed to increase flexibility in the lower back.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "expert",
    durationMinutes: 17,
    bodyAreas: ["lower-back"],
    exercises: [
      { exerciseId: "rag-doll", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "lunge", holdSeconds: 120, sides: "both", order: 2 },
      { exerciseId: "childs-pose", holdSeconds: 60, sides: "none", order: 3 },
      { exerciseId: "cat-cow", holdSeconds: 60, sides: "none", order: 4 },
      { exerciseId: "thunderbolt", holdSeconds: 60, sides: "none", order: 5 },
      { exerciseId: "seated-fold", holdSeconds: 60, sides: "none", order: 6 },
      { exerciseId: "seated-straddle", holdSeconds: 60, sides: "none", order: 7 },
      { exerciseId: "knees-to-chest", holdSeconds: 60, sides: "none", order: 8 },
      { exerciseId: "lying-figure-four", holdSeconds: 120, sides: "both", order: 9 },
      { exerciseId: "happy-baby", holdSeconds: 60, sides: "none", order: 10 },
      { exerciseId: "legs-up-wall", holdSeconds: 60, sides: "none", order: 11 },
    ],
    tags: ["targeted","deep-stretch","expert","lower-back"],
  },
  {
    id: "targeted-splits",
    name: "Targeted Splits",
    description: "Deepen your front splits with a daily routine designed to target your hips, hamstrings, and glutes.",
    category: "targeted",
    routineType: "deep-stretch",
    difficulty: "expert",
    durationMinutes: 28,
    bodyAreas: ["splits"],
    exercises: [
      { exerciseId: "reverse-lunge", holdSeconds: 120, sides: "both", order: 1 },
      { exerciseId: "lizard-pose", holdSeconds: 120, sides: "both", order: 2 },
      { exerciseId: "hamstring-pulls", holdSeconds: 120, sides: "both", order: 3 },
      { exerciseId: "kneeling-quad", holdSeconds: 120, sides: "both", order: 4 },
      { exerciseId: "side-lunge", holdSeconds: 120, sides: "both", order: 5 },
      { exerciseId: "lunge", holdSeconds: 120, sides: "both", order: 6 },
      { exerciseId: "front-split", holdSeconds: 120, sides: "both", order: 7 },
    ],
    tags: ["targeted","deep-stretch","expert","splits"],
  },
  {
    id: "neck-1",
    name: "Neck 1",
    description: "A series of stretches designed to increase flexibility in the neck.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 6,
    bodyAreas: ["neck","upper-body"],
    exercises: [
      { exerciseId: "chin-retractions", holdSeconds: 22, sides: "none", order: 1 },
      { exerciseId: "neck-roll", holdSeconds: 22, sides: "none", order: 2 },
      { exerciseId: "shoulder-rolls", holdSeconds: 22, sides: "both", order: 3 },
      { exerciseId: "cactus-arms", holdSeconds: 22, sides: "none", order: 4 },
      { exerciseId: "diver", holdSeconds: 22, sides: "none", order: 5 },
      { exerciseId: "ear-to-shoulder", holdSeconds: 22, sides: "both", order: 6 },
      { exerciseId: "neck-extension", holdSeconds: 22, sides: "none", order: 7 },
      { exerciseId: "neck-flexion", holdSeconds: 22, sides: "none", order: 8 },
      { exerciseId: "neck-rotation", holdSeconds: 22, sides: "both", order: 9 },
      { exerciseId: "scalene-stretch", holdSeconds: 22, sides: "both", order: 10 },
      { exerciseId: "scapula-stretch", holdSeconds: 22, sides: "both", order: 11 },
    ],
    tags: ["body-part","stretching","beginner","neck","upper-body"],
  },
  {
    id: "shoulders-1",
    name: "Shoulders 1",
    description: "A series of stretches designed to increase flexibility in the shoulders.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: ["shoulders","upper-body"],
    exercises: [
      { exerciseId: "chest-opener", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "diver", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "doorway-pecs", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "forward-fold", holdSeconds: 30, sides: "none", order: 4 },
      { exerciseId: "one-arm-hug", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "overhead-tricep", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "reverse-shoulder", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "wall-arms", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "wall-dog", holdSeconds: 30, sides: "none", order: 9 },
      { exerciseId: "wall-pecs", holdSeconds: 30, sides: "both", order: 10 },
    ],
    tags: ["body-part","stretching","beginner","shoulders","upper-body"],
  },
  {
    id: "chest-1",
    name: "Chest 1",
    description: "A series of stretches designed to increase flexibility in the chest.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 8,
    bodyAreas: ["chest","upper-body"],
    exercises: [
      { exerciseId: "arm-swings", holdSeconds: 38, sides: "none", order: 1 },
      { exerciseId: "chest-opener", holdSeconds: 38, sides: "none", order: 2 },
      { exerciseId: "doorway-pecs", holdSeconds: 38, sides: "none", order: 3 },
      { exerciseId: "one-arm-hug", holdSeconds: 38, sides: "both", order: 4 },
      { exerciseId: "overhead-tricep", holdSeconds: 38, sides: "both", order: 5 },
      { exerciseId: "reverse-shoulder", holdSeconds: 38, sides: "none", order: 6 },
      { exerciseId: "wall-arms", holdSeconds: 38, sides: "both", order: 7 },
      { exerciseId: "wall-pecs", holdSeconds: 38, sides: "both", order: 8 },
    ],
    tags: ["body-part","stretching","beginner","chest","upper-body"],
  },
  {
    id: "lower-back-1",
    name: "Lower Back 1",
    description: "A series of stretches designed to increase flexibility in the lower back.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: ["core","lower-back"],
    exercises: [
      { exerciseId: "butterfly", holdSeconds: 43, sides: "none", order: 1 },
      { exerciseId: "cat-cow", holdSeconds: 43, sides: "none", order: 2 },
      { exerciseId: "downward-dog", holdSeconds: 43, sides: "none", order: 3 },
      { exerciseId: "knees-to-chest", holdSeconds: 43, sides: "none", order: 4 },
      { exerciseId: "lying-figure-four", holdSeconds: 43, sides: "both", order: 5 },
      { exerciseId: "reverse-lunge", holdSeconds: 43, sides: "both", order: 6 },
      { exerciseId: "spinal-twist", holdSeconds: 43, sides: "both", order: 7 },
    ],
    tags: ["body-part","stretching","beginner","core","lower-back"],
  },
  {
    id: "hips-1",
    name: "Hips 1",
    description: "A series of stretches designed to increase flexibility in the hips.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 9,
    bodyAreas: ["hips","lower-body"],
    exercises: [
      { exerciseId: "butterfly", holdSeconds: 60, sides: "none", order: 1 },
      { exerciseId: "lunge", holdSeconds: 60, sides: "both", order: 2 },
      { exerciseId: "lying-figure-four", holdSeconds: 60, sides: "both", order: 3 },
      { exerciseId: "quad-stretch", holdSeconds: 60, sides: "both", order: 4 },
      { exerciseId: "spinal-twist", holdSeconds: 60, sides: "both", order: 5 },
    ],
    tags: ["body-part","stretching","beginner","hips","lower-body"],
  },
  {
    id: "hamstrings-1",
    name: "Hamstrings 1",
    description: "A series of stretches designed to increase flexibility in the hamstrings.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 8,
    bodyAreas: ["hamstrings","lower-body"],
    exercises: [
      { exerciseId: "cross-leg-fold", holdSeconds: 43, sides: "both", order: 1 },
      { exerciseId: "hurdler", holdSeconds: 43, sides: "both", order: 2 },
      { exerciseId: "reverse-lunge", holdSeconds: 43, sides: "both", order: 3 },
      { exerciseId: "seated-fold", holdSeconds: 43, sides: "none", order: 4 },
      { exerciseId: "side-lunge", holdSeconds: 43, sides: "both", order: 5 },
      { exerciseId: "toe-touch", holdSeconds: 43, sides: "none", order: 6 },
      { exerciseId: "wide-leg-bend", holdSeconds: 43, sides: "none", order: 7 },
    ],
    tags: ["body-part","stretching","beginner","hamstrings","lower-body"],
  },
  {
    id: "quads-1",
    name: "Quads 1",
    description: "A series of stretches designed to increase flexibility in the quadriceps.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 10,
    bodyAreas: ["lower-body","quadriceps"],
    exercises: [
      { exerciseId: "kneeling-quad", holdSeconds: 75, sides: "both", order: 1 },
      { exerciseId: "lizard-pose", holdSeconds: 75, sides: "both", order: 2 },
      { exerciseId: "quad-stretch", holdSeconds: 75, sides: "both", order: 3 },
      { exerciseId: "standing-quad", holdSeconds: 75, sides: "both", order: 4 },
    ],
    tags: ["body-part","stretching","beginner","lower-body","quadriceps"],
  },
  {
    id: "feet-and-ankles-1",
    name: "Feet & Ankles 1",
    description: "A targeted series of dynamic exercises and stretches for foot and ankle range of motion.",
    category: "body-part",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 9,
    bodyAreas: ["feet-and-ankles","lower-body"],
    exercises: [
      { exerciseId: "single-leg-stand", holdSeconds: 43, sides: "both", order: 1 },
      { exerciseId: "ankle-circles", holdSeconds: 43, sides: "both", order: 2 },
      { exerciseId: "heel-to-toe-rocks", holdSeconds: 43, sides: "none", order: 3 },
      { exerciseId: "knee-circles", holdSeconds: 43, sides: "both", order: 4 },
      { exerciseId: "lateral-foot-rocks", holdSeconds: 43, sides: "none", order: 5 },
      { exerciseId: "soleus-stretch", holdSeconds: 43, sides: "both", order: 6 },
      { exerciseId: "standing-quad", holdSeconds: 43, sides: "both", order: 7 },
    ],
    tags: ["body-part","stretching","beginner","feet-and-ankles","lower-body"],
  },
  {
    id: "pelvic-floor-2",
    name: "Pelvic Floor 2",
    description: "A series of stretches and isometric exercises for pelvic floor, hips, and core.",
    category: "pelvic-floor",
    routineType: "stretching",
    difficulty: "intermediate",
    durationMinutes: 13,
    bodyAreas: [],
    exercises: [
      { exerciseId: "pelvic-tilt-press", holdSeconds: 38, sides: "none", order: 1 },
      { exerciseId: "butterfly", holdSeconds: 38, sides: "none", order: 2 },
      { exerciseId: "cat-cow", holdSeconds: 38, sides: "none", order: 3 },
      { exerciseId: "childs-pose", holdSeconds: 38, sides: "none", order: 4 },
      { exerciseId: "frog-pose", holdSeconds: 38, sides: "none", order: 5 },
      { exerciseId: "happy-baby", holdSeconds: 38, sides: "none", order: 6 },
      { exerciseId: "knees-to-chest", holdSeconds: 38, sides: "none", order: 7 },
      { exerciseId: "lunge", holdSeconds: 38, sides: "both", order: 8 },
      { exerciseId: "lying-figure-four", holdSeconds: 38, sides: "both", order: 9 },
      { exerciseId: "reclined-butterfly", holdSeconds: 38, sides: "none", order: 10 },
      { exerciseId: "reverse-lunge", holdSeconds: 38, sides: "both", order: 11 },
      { exerciseId: "spinal-twist", holdSeconds: 38, sides: "both", order: 12 },
      { exerciseId: "upward-dog", holdSeconds: 38, sides: "none", order: 13 },
      { exerciseId: "upward-salute", holdSeconds: 38, sides: "none", order: 14 },
      { exerciseId: "wide-leg-bend", holdSeconds: 38, sides: "none", order: 15 },
      { exerciseId: "bridge", holdSeconds: 38, sides: "none", order: 16 },
    ],
    tags: ["pelvic-floor","stretching","intermediate"],
  },
  {
    id: "pelvic-floor-3",
    name: "Pelvic Floor 3",
    description: "A series of stretches and isometric exercises for pelvic floor, hips, and core.",
    category: "pelvic-floor",
    routineType: "stretching",
    difficulty: "expert",
    durationMinutes: 20,
    bodyAreas: [],
    exercises: [
      { exerciseId: "pelvic-tilt-press", holdSeconds: 38, sides: "none", order: 1 },
      { exerciseId: "hip-circles", holdSeconds: 38, sides: "both", order: 2 },
      { exerciseId: "butterfly", holdSeconds: 38, sides: "none", order: 3 },
      { exerciseId: "cat-cow", holdSeconds: 38, sides: "none", order: 4 },
      { exerciseId: "childs-pose", holdSeconds: 38, sides: "none", order: 5 },
      { exerciseId: "downward-dog", holdSeconds: 38, sides: "none", order: 6 },
      { exerciseId: "frog-pose", holdSeconds: 38, sides: "none", order: 7 },
      { exerciseId: "happy-baby", holdSeconds: 38, sides: "none", order: 8 },
      { exerciseId: "knees-to-chest", holdSeconds: 38, sides: "none", order: 9 },
      { exerciseId: "lizard-pose", holdSeconds: 38, sides: "both", order: 10 },
      { exerciseId: "lunge", holdSeconds: 38, sides: "both", order: 11 },
      { exerciseId: "lying-figure-four", holdSeconds: 38, sides: "both", order: 12 },
      { exerciseId: "reclined-butterfly", holdSeconds: 38, sides: "none", order: 13 },
      { exerciseId: "reverse-lunge", holdSeconds: 38, sides: "both", order: 14 },
      { exerciseId: "reverse-shoulder", holdSeconds: 38, sides: "none", order: 15 },
      { exerciseId: "side-lunge", holdSeconds: 38, sides: "both", order: 16 },
      { exerciseId: "spinal-twist", holdSeconds: 38, sides: "both", order: 17 },
      { exerciseId: "squat-stretch", holdSeconds: 38, sides: "none", order: 18 },
      { exerciseId: "toe-touch", holdSeconds: 38, sides: "none", order: 19 },
      { exerciseId: "upward-dog", holdSeconds: 38, sides: "none", order: 20 },
      { exerciseId: "upward-salute", holdSeconds: 38, sides: "none", order: 21 },
      { exerciseId: "wide-leg-bend", holdSeconds: 38, sides: "none", order: 22 },
      { exerciseId: "bird-dog", holdSeconds: 38, sides: "both", order: 23 },
      { exerciseId: "bridge", holdSeconds: 38, sides: "none", order: 24 },
    ],
    tags: ["pelvic-floor","stretching","expert"],
  },
  {
    id: "pelvic-floor-4",
    name: "Pelvic Floor 4",
    description: "A series of stretches and isometric exercises for pelvic floor, hips, and core.",
    category: "pelvic-floor",
    routineType: "stretching",
    difficulty: "expert",
    durationMinutes: 29,
    bodyAreas: [],
    exercises: [
      { exerciseId: "pelvic-tilt-press", holdSeconds: 40, sides: "none", order: 1 },
      { exerciseId: "hip-circles", holdSeconds: 40, sides: "both", order: 2 },
      { exerciseId: "butterfly", holdSeconds: 40, sides: "none", order: 3 },
      { exerciseId: "cat-cow", holdSeconds: 40, sides: "none", order: 4 },
      { exerciseId: "childs-pose", holdSeconds: 40, sides: "none", order: 5 },
      { exerciseId: "downward-dog", holdSeconds: 40, sides: "none", order: 6 },
      { exerciseId: "frog-pose", holdSeconds: 40, sides: "none", order: 7 },
      { exerciseId: "happy-baby", holdSeconds: 40, sides: "none", order: 8 },
      { exerciseId: "knees-to-chest", holdSeconds: 40, sides: "none", order: 9 },
      { exerciseId: "lizard-pose", holdSeconds: 40, sides: "both", order: 10 },
      { exerciseId: "lunge", holdSeconds: 40, sides: "both", order: 11 },
      { exerciseId: "lying-figure-four", holdSeconds: 40, sides: "both", order: 12 },
      { exerciseId: "pigeon", holdSeconds: 40, sides: "both", order: 13 },
      { exerciseId: "reclined-butterfly", holdSeconds: 40, sides: "none", order: 14 },
      { exerciseId: "reverse-lunge", holdSeconds: 40, sides: "both", order: 15 },
      { exerciseId: "reverse-shoulder", holdSeconds: 40, sides: "none", order: 16 },
      { exerciseId: "seated-twist", holdSeconds: 40, sides: "both", order: 17 },
      { exerciseId: "side-lunge", holdSeconds: 40, sides: "both", order: 18 },
      { exerciseId: "single-knee-to-chest", holdSeconds: 40, sides: "both", order: 19 },
      { exerciseId: "spinal-twist", holdSeconds: 40, sides: "both", order: 20 },
      { exerciseId: "squat-stretch", holdSeconds: 40, sides: "none", order: 21 },
      { exerciseId: "toe-touch", holdSeconds: 40, sides: "none", order: 22 },
      { exerciseId: "upward-dog", holdSeconds: 40, sides: "none", order: 23 },
      { exerciseId: "upward-frog", holdSeconds: 40, sides: "both", order: 24 },
      { exerciseId: "upward-salute", holdSeconds: 40, sides: "none", order: 25 },
      { exerciseId: "wide-leg-bend", holdSeconds: 40, sides: "none", order: 26 },
      { exerciseId: "bird-dog", holdSeconds: 40, sides: "both", order: 27 },
      { exerciseId: "bridge", holdSeconds: 40, sides: "none", order: 28 },
      { exerciseId: "dead-bug", holdSeconds: 40, sides: "both", order: 29 },
      { exerciseId: "elbow-plank", holdSeconds: 40, sides: "none", order: 30 },
    ],
    tags: ["pelvic-floor","stretching","expert"],
  },
  {
    id: "pelvic-floor-5",
    name: "Pelvic Floor 5",
    description: "A series of stretches and isometric exercises for pelvic floor, hips, and core.",
    category: "pelvic-floor",
    routineType: "stretching",
    difficulty: "expert",
    durationMinutes: 36,
    bodyAreas: [],
    exercises: [
      { exerciseId: "pelvic-tilt-press", holdSeconds: 41, sides: "none", order: 1 },
      { exerciseId: "hip-circles", holdSeconds: 41, sides: "both", order: 2 },
      { exerciseId: "knees-hugs", holdSeconds: 41, sides: "none", order: 3 },
      { exerciseId: "butterfly", holdSeconds: 41, sides: "none", order: 4 },
      { exerciseId: "cat-cow", holdSeconds: 41, sides: "none", order: 5 },
      { exerciseId: "childs-pose", holdSeconds: 41, sides: "none", order: 6 },
      { exerciseId: "downward-dog", holdSeconds: 41, sides: "none", order: 7 },
      { exerciseId: "folded-butterfly", holdSeconds: 41, sides: "none", order: 8 },
      { exerciseId: "frog-pose", holdSeconds: 41, sides: "none", order: 9 },
      { exerciseId: "happy-baby", holdSeconds: 41, sides: "none", order: 10 },
      { exerciseId: "hurdler", holdSeconds: 41, sides: "both", order: 11 },
      { exerciseId: "kneeling-psoas", holdSeconds: 41, sides: "both", order: 12 },
      { exerciseId: "knees-to-chest", holdSeconds: 41, sides: "none", order: 13 },
      { exerciseId: "lizard-pose", holdSeconds: 41, sides: "both", order: 14 },
      { exerciseId: "lunge", holdSeconds: 41, sides: "both", order: 15 },
      { exerciseId: "lying-figure-four", holdSeconds: 41, sides: "both", order: 16 },
      { exerciseId: "pigeon", holdSeconds: 41, sides: "both", order: 17 },
      { exerciseId: "puppy-pose", holdSeconds: 41, sides: "none", order: 18 },
      { exerciseId: "quad-stretch", holdSeconds: 41, sides: "both", order: 19 },
      { exerciseId: "reclined-butterfly", holdSeconds: 41, sides: "none", order: 20 },
      { exerciseId: "reverse-lunge", holdSeconds: 41, sides: "both", order: 21 },
      { exerciseId: "reverse-shoulder", holdSeconds: 41, sides: "none", order: 22 },
      { exerciseId: "seated-twist", holdSeconds: 41, sides: "both", order: 23 },
      { exerciseId: "side-lunge", holdSeconds: 41, sides: "both", order: 24 },
      { exerciseId: "single-knee-to-chest", holdSeconds: 41, sides: "both", order: 25 },
      { exerciseId: "spinal-twist", holdSeconds: 41, sides: "both", order: 26 },
      { exerciseId: "squat-stretch", holdSeconds: 41, sides: "none", order: 27 },
      { exerciseId: "standing-frog", holdSeconds: 41, sides: "none", order: 28 },
      { exerciseId: "toe-touch", holdSeconds: 41, sides: "none", order: 29 },
      { exerciseId: "upward-dog", holdSeconds: 41, sides: "none", order: 30 },
      { exerciseId: "upward-frog", holdSeconds: 41, sides: "both", order: 31 },
      { exerciseId: "upward-salute", holdSeconds: 41, sides: "none", order: 32 },
      { exerciseId: "wide-leg-bend", holdSeconds: 41, sides: "none", order: 33 },
      { exerciseId: "bird-dog", holdSeconds: 41, sides: "both", order: 34 },
      { exerciseId: "bridge", holdSeconds: 41, sides: "none", order: 35 },
      { exerciseId: "dead-bug", holdSeconds: 41, sides: "both", order: 36 },
      { exerciseId: "elbow-plank", holdSeconds: 41, sides: "none", order: 37 },
    ],
    tags: ["pelvic-floor","stretching","expert"],
  },
  {
    id: "upper-body-1",
    name: "Upper Body 1",
    description: "A beginner routine for neck, shoulders, chest, and upper back.",
    category: "beginner-series",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 8,
    bodyAreas: ["upper-body"],
    exercises: [
      { exerciseId: "chin-retractions", holdSeconds: 30, sides: "none", order: 1 },
      { exerciseId: "neck-roll", holdSeconds: 30, sides: "none", order: 2 },
      { exerciseId: "diver", holdSeconds: 30, sides: "none", order: 3 },
      { exerciseId: "ear-to-shoulder", holdSeconds: 30, sides: "both", order: 4 },
      { exerciseId: "one-arm-hug", holdSeconds: 30, sides: "both", order: 5 },
      { exerciseId: "overhead-tricep", holdSeconds: 30, sides: "both", order: 6 },
      { exerciseId: "reverse-shoulder", holdSeconds: 30, sides: "none", order: 7 },
      { exerciseId: "scalene-stretch", holdSeconds: 30, sides: "both", order: 8 },
      { exerciseId: "scapula-stretch", holdSeconds: 30, sides: "both", order: 9 },
      { exerciseId: "wall-arms", holdSeconds: 30, sides: "both", order: 10 },
    ],
    tags: ["beginner-series","stretching","beginner","upper-body"],
  },
  {
    id: "lower-body-1",
    name: "Lower Body 1",
    description: "A beginner routine for hips, hamstrings, glutes, groin, and thighs.",
    category: "beginner-series",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 9,
    bodyAreas: ["lower-body"],
    exercises: [
      { exerciseId: "butterfly", holdSeconds: 75, sides: "none", order: 1 },
      { exerciseId: "lunge", holdSeconds: 75, sides: "both", order: 2 },
      { exerciseId: "lying-figure-four", holdSeconds: 75, sides: "both", order: 3 },
      { exerciseId: "quad-stretch", holdSeconds: 75, sides: "both", order: 4 },
    ],
    tags: ["beginner-series","stretching","beginner","lower-body"],
  },
  {
    id: "core-1",
    name: "Core 1",
    description: "A beginner routine for lower back, hips, and core.",
    category: "beginner-series",
    routineType: "stretching",
    difficulty: "beginner",
    durationMinutes: 7,
    bodyAreas: ["core"],
    exercises: [
      { exerciseId: "childs-pose", holdSeconds: 43, sides: "none", order: 1 },
      { exerciseId: "knees-to-chest", holdSeconds: 43, sides: "none", order: 2 },
      { exerciseId: "lying-figure-four", holdSeconds: 43, sides: "both", order: 3 },
      { exerciseId: "single-knee-to-chest", holdSeconds: 43, sides: "both", order: 4 },
      { exerciseId: "spinal-twist", holdSeconds: 43, sides: "both", order: 5 },
      { exerciseId: "upward-dog", holdSeconds: 43, sides: "none", order: 6 },
      { exerciseId: "upward-salute", holdSeconds: 43, sides: "none", order: 7 },
    ],
    tags: ["beginner-series","stretching","beginner","core"],
  },
];
